/****** Object:  Table [dbo].[LACK1_CALCULATION_DETAIL]    Script Date: 8/21/2017 1:15:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK1_CALCULATION_DETAIL](
	[LACK1_CALCULATION_DETAIL_ID] [int] NOT NULL,
	[LACK1_ID] [int] NOT NULL,
	[MATERIAL_ID] [nvarchar](18) NULL,
	[PLANT_ID] [nvarchar](4) NULL,
	[AMOUNT_USAGE] [decimal](18, 3) NULL,
	[ORDR] [nvarchar](10) NULL,
	[FA_CODE] [nvarchar](18) NULL,
	[AMOUNT_PRODUCTION] [decimal](18, 3) NULL,
	[PROPORTIONAL] [decimal](18, 8) NULL,
	[TYPE] [int] NULL,
 CONSTRAINT [PK_LACK1_CALCULATION_DETAIL] PRIMARY KEY CLUSTERED 
(
	[LACK1_CALCULATION_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK1_CALCULATION_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_LACK1_CALCULATION_DETAIL_LACK1] FOREIGN KEY([LACK1_ID])
REFERENCES [dbo].[LACK1] ([LACK1_ID])
GO

ALTER TABLE [dbo].[LACK1_CALCULATION_DETAIL] CHECK CONSTRAINT [FK_LACK1_CALCULATION_DETAIL_LACK1]
GO


