/****** Object:  Table [dbo].[LACK1_PERIOD_SUMMARY]    Script Date: 8/24/2017 10:52:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK1_PERIOD_SUMMARY](
	[LACK1_SUMMARY_ID] [int] IDENTITY(1,1) NOT NULL,
	[LACK1_ID] [int] NULL,
	[INCOME] [decimal](18, 3) NULL,
	[USAGE] [decimal](18, 3) NULL,
	[LABORATORIUM] [decimal](18, 3) NULL,
	[CK5_RETURN] [decimal](18, 3) NULL,
	[SALDO] [decimal](18, 3) NULL,
	[TYPE] [int] NULL,
 CONSTRAINT [PK_LACK1_PERIOD_SUMMARY] PRIMARY KEY CLUSTERED 
(
	[LACK1_SUMMARY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE dbo.LACK1_PERIOD_SUMMARY ADD CONSTRAINT
	FK_LACK1_PERIOD_SUMMARY_LACK1 FOREIGN KEY
	(
	LACK1_ID
	) REFERENCES dbo.LACK1
	(
	LACK1_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.LACK1_PERIOD_SUMMARY SET (LOCK_ESCALATION = TABLE)
GO