/****** Object:  Table [dbo].[LACK10]    Script Date: 22/08/2017 10:49:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK10](
	[LACK10_ID] [int] IDENTITY(1,1) NOT NULL,
	[LACK10_NUMBER] [nvarchar](50) NOT NULL,
	[COMPANY_ID] [nvarchar](4) NOT NULL,
	[COMPANY_NAME] [nvarchar](50) NOT NULL,
	[COMPANY_NPWP] [nvarchar](30) NOT NULL,
	[PERIOD_MONTH] [int] NOT NULL,
	[PERIOD_YEAR] [int] NOT NULL,
	[NPPBKC_ID] [nvarchar](15) NOT NULL,
	[PLANT_ID] [nvarchar](4) NULL,
	[PLANT_NAME] [nvarchar](30) NULL,
	[SUBMISSION_DATE] [datetime] NOT NULL,
	[REPORT_TYPE] [int] NOT NULL,
	[STATUS] [int] NOT NULL,
	[GOV_STATUS] [int] NULL,
	[DECREE_DATE] [datetime] NULL,
	[REASON] [nvarchar](250) NULL,
	[REMARK] [nvarchar](250) NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
	[APPROVED_BY_MANAGER] [nvarchar](50) NULL,
	[APPROVED_BY_MANAGER_DATE] [datetime] NULL,
	[REJECTED_BY] [nvarchar](50) NULL,
	[REJECTED_DATE] [datetime] NULL,
 CONSTRAINT [PK_LACK10] PRIMARY KEY CLUSTERED 
(
	[LACK10_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK10]  WITH CHECK ADD  CONSTRAINT [FK_LACK10_MONTH] FOREIGN KEY([PERIOD_MONTH])
REFERENCES [dbo].[MONTH] ([MONTH_ID])
GO

ALTER TABLE [dbo].[LACK10] CHECK CONSTRAINT [FK_LACK10_MONTH]
GO

ALTER TABLE [dbo].[LACK10]  WITH CHECK ADD  CONSTRAINT [FK_LACK10_USER_APPROVED_BY] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK10] CHECK CONSTRAINT [FK_LACK10_USER_APPROVED_BY]
GO

ALTER TABLE [dbo].[LACK10]  WITH CHECK ADD  CONSTRAINT [FK_LACK10_USER_CREATED_BY] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK10] CHECK CONSTRAINT [FK_LACK10_USER_CREATED_BY]
GO

ALTER TABLE [dbo].[LACK10]  WITH CHECK ADD  CONSTRAINT [FK_LACK10_USER_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK10] CHECK CONSTRAINT [FK_LACK10_USER_MODIFIED_BY]
GO


