//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACK1_DOCUMENT
    {
        public long BACK1_DOCUMENT_ID { get; set; }
        public int BACK1 { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
    
        public virtual BACK1 BACK11 { get; set; }
    }
}
