//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACK1
    {
        public BACK1()
        {
            this.BACK1_DOCUMENT = new HashSet<BACK1_DOCUMENT>();
        }
    
        public int BACK1_ID { get; set; }
        public string BACK1_NUMBER { get; set; }
        public System.DateTime BACK1_DATE { get; set; }
        public Nullable<int> PBCK7_ID { get; set; }
        public Nullable<long> CK5_ID { get; set; }
    
        public virtual CK5 CK5 { get; set; }
        public virtual ICollection<BACK1_DOCUMENT> BACK1_DOCUMENT { get; set; }
        public virtual PBCK7 PBCK7 { get; set; }
    }
}
