//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACK1
    {
        public BACK1()
        {
            this.PBCK4 = new HashSet<PBCK4>();
        }
    
        public long BACK1_ID { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> STATUS_GOV_ID { get; set; }
    
        public virtual STATUS_GOV STATUS_GOV { get; set; }
        public virtual ICollection<PBCK4> PBCK4 { get; set; }
    }
}
