//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOCK_STOCK
    {
        public long BLOCK_STOCK_ID { get; set; }
        public string MATERIAL_ID { get; set; }
        public string PLANT { get; set; }
        public Nullable<decimal> BLOCKED { get; set; }
        public string BUN { get; set; }
    }
}
