//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BROLE_MAP
    {
        public int BROLE_MAP_ID { get; set; }
        public string BROLE { get; set; }
        public string MSACCT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER_BROLE USER_BROLE { get; set; }
    }
}
