//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CK1_ITEM
    {
        public long CK1_ITEM_ID { get; set; }
        public Nullable<long> CK1_ID { get; set; }
        public string MATERIAL_ID { get; set; }
        public string WERKS { get; set; }
        public string FA_CODE { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string UOM { get; set; }
    
        public virtual CK1 CK1 { get; set; }
    }
}
