//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CK2
    {
        public CK2()
        {
            this.PBCK3_7 = new HashSet<PBCK3_7>();
            this.PBCK3_CK5 = new HashSet<PBCK3_CK5>();
        }
    
        public long CK2_ID { get; set; }
        public string CK2_NUMBER { get; set; }
        public Nullable<System.DateTime> CK2_DATE { get; set; }
        public Nullable<int> STATUS_GOV { get; set; }
    
        public virtual STATUS_GOV STATUS_GOV1 { get; set; }
        public virtual ICollection<PBCK3_7> PBCK3_7 { get; set; }
        public virtual ICollection<PBCK3_CK5> PBCK3_CK5 { get; set; }
    }
}
