//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CK4C_REPORT_ITEM
    {
        public long CK4C_REPORT_ITEM_ID { get; set; }
        public Nullable<int> CK4C_ID { get; set; }
        public string PROD_CODE { get; set; }
        public string PROD_TYPE { get; set; }
        public string MERK { get; set; }
        public string HJE { get; set; }
        public string NO_ITEM { get; set; }
        public string NO_PROD { get; set; }
        public string PROD_DATE { get; set; }
        public string SUM_BTG { get; set; }
        public string BTG_GR { get; set; }
        public string ISI { get; set; }
        public string TOTAL { get; set; }
        public string PROD_WASTE { get; set; }
        public string COMMENT_ITEM { get; set; }
        public Nullable<int> COLLUM_NO { get; set; }
    }
}
