//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_NUMBER_SEQ
    {
        public long DOC_NUMBER_SEQ_ID { get; set; }
        public long DOC_NUMBER_SEQ_LAST { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> YEAR { get; set; }
    
        public virtual MONTH MONTH1 { get; set; }
    }
}
