//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_GOODS_DECS
    {
        public EX_GOODS_DECS()
        {
            this.PBCK1 = new HashSet<PBCK1>();
        }
    
        public int EX_GOODS_DECS_ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<PBCK1> PBCK1 { get; set; }
    }
}
