//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_TYPE
    {
        public FORM_TYPE()
        {
            this.CHANGES_HISTORY = new HashSet<CHANGES_HISTORY>();
            this.FILE_UPLOAD = new HashSet<FILE_UPLOAD>();
            this.WORKFLOW_HISTORY = new HashSet<WORKFLOW_HISTORY>();
        }
    
        public int FORM_TYPE_ID { get; set; }
        public string FORM_NAME { get; set; }
    
        public virtual ICollection<CHANGES_HISTORY> CHANGES_HISTORY { get; set; }
        public virtual ICollection<FILE_UPLOAD> FILE_UPLOAD { get; set; }
        public virtual ICollection<WORKFLOW_HISTORY> WORKFLOW_HISTORY { get; set; }
    }
}
