//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEADER_FOOTER_FORM_MAP
    {
        public int HEADER_FOOTER_FORM_MAP_ID { get; set; }
        public int HEADER_FOOTER_ID { get; set; }
        public Nullable<int> FORM_TYPE_ID { get; set; }
        public Nullable<bool> IS_HEADER_SET { get; set; }
        public Nullable<bool> IS_FOOTER_SET { get; set; }
    
        public virtual HEADER_FOOTER HEADER_FOOTER { get; set; }
    }
}
