//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK2
    {
        public LACK2()
        {
            this.LACK2_DOCUMENT = new HashSet<LACK2_DOCUMENT>();
            this.LACK2_ITEM = new HashSet<LACK2_ITEM>();
        }
    
        public int LACK2_ID { get; set; }
        public string BUKRS { get; set; }
        public string BUTXT { get; set; }
        public int PERIOD_MONTH { get; set; }
        public int PERIOD_YEAR { get; set; }
        public string LEVEL_PLANT_ID { get; set; }
        public string LEVEL_PLANT_NAME { get; set; }
        public string LEVEL_PLANT_CITY { get; set; }
        public System.DateTime SUBMISSION_DATE { get; set; }
        public string EX_GOOD_TYP { get; set; }
        public string EX_TYP_DESC { get; set; }
        public int GOV_STATUS { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> DECREE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string NPPBKC_ID { get; set; }
        public string LACK2_NUMBER { get; set; }
    
        public virtual ICollection<LACK2_DOCUMENT> LACK2_DOCUMENT { get; set; }
        public virtual ICollection<LACK2_ITEM> LACK2_ITEM { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USER USER2 { get; set; }
    }
}
