//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK1
    {
        public LACK1()
        {
            this.LACK1_DOCUMENT = new HashSet<LACK1_DOCUMENT>();
            this.LACK1_ITEM = new HashSet<LACK1_ITEM>();
        }
    
        public int LACK1_ID { get; set; }
        public string LACK1_NUMBER { get; set; }
        public string BUKRS { get; set; }
        public string BUTXT { get; set; }
        public Nullable<int> PERIOD_MONTH { get; set; }
        public Nullable<int> PERIOD_YEAR { get; set; }
        public string LEVEL_PLANT_ID { get; set; }
        public string LEVEL_PLANT_NAME { get; set; }
        public Nullable<System.DateTime> SUBMISSION_DATE { get; set; }
        public string SUPPLIER_PLANT { get; set; }
        public string EX_GOODTYP { get; set; }
        public Nullable<decimal> WASTE_QTY { get; set; }
        public string WASTE_UOM { get; set; }
        public Nullable<decimal> RETURN_QTY { get; set; }
        public string RETURN_UOM { get; set; }
        public Nullable<Sampoerna.EMS.Core.Enums.DocumentStatus> STATUS { get; set; }
        public Nullable<Sampoerna.EMS.Core.Enums.DocumentStatusGov> GOV_STATUS { get; set; }
        public Nullable<System.DateTime> DECREE_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
    
        public virtual ICollection<LACK1_DOCUMENT> LACK1_DOCUMENT { get; set; }
        public virtual ICollection<LACK1_ITEM> LACK1_ITEM { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual UOM UOM1 { get; set; }
    }
}
