//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK1_PERIOD_SUMMARY
    {
        public int LACK1_SUMMARY_ID { get; set; }
        public Nullable<int> LACK1_ID { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public Nullable<decimal> USAGE { get; set; }
        public Nullable<decimal> LABORATORIUM { get; set; }
        public Nullable<decimal> CK5_RETURN { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<int> TYPE { get; set; }
    
        public virtual LACK1 LACK1 { get; set; }
    }
}
