//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK1_ITEM
    {
        public long LACK1_ITEM_ID { get; set; }
        public Nullable<int> LACK1_ID { get; set; }
        public Nullable<decimal> BEGINNING_BALANCE { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public Nullable<decimal> USAGE { get; set; }
        public Nullable<decimal> PRODUCTION { get; set; }
    
        public virtual LACK1 LACK1 { get; set; }
    }
}
