//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK10
    {
        public LACK10()
        {
            this.LACK10_DECREE_DOC = new HashSet<LACK10_DECREE_DOC>();
            this.LACK10_ITEM = new HashSet<LACK10_ITEM>();
        }
    
        public int LACK10_ID { get; set; }
        public string LACK10_NUMBER { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_NPWP { get; set; }
        public int PERIOD_MONTH { get; set; }
        public int PERIOD_YEAR { get; set; }
        public string NPPBKC_ID { get; set; }
        public string PLANT_ID { get; set; }
        public string PLANT_NAME { get; set; }
        public System.DateTime SUBMISSION_DATE { get; set; }
        public int REPORT_TYPE { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> GOV_STATUS { get; set; }
        public Nullable<System.DateTime> DECREE_DATE { get; set; }
        public string REASON { get; set; }
        public string REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string APPROVED_BY_MANAGER { get; set; }
        public Nullable<System.DateTime> APPROVED_BY_MANAGER_DATE { get; set; }
        public string REJECTED_BY { get; set; }
        public Nullable<System.DateTime> REJECTED_DATE { get; set; }
    
        public virtual ICollection<LACK10_DECREE_DOC> LACK10_DECREE_DOC { get; set; }
        public virtual ICollection<LACK10_ITEM> LACK10_ITEM { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USER USER2 { get; set; }
    }
}
