//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LACK1_PBCK1_MAPPING
    {
        public long LACK1_PBCK1_MAPPING_ID { get; set; }
        public int LACK1_ID { get; set; }
        public int PBCK1_ID { get; set; }
    
        public virtual LACK1 LACK1 { get; set; }
        public virtual PBCK1 PBCK1 { get; set; }
    }
}
