//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_UOM
    {
        public long MATERIAL_UOM_ID { get; set; }
        public string STICKER_CODE { get; set; }
        public string WERKS { get; set; }
        public string MEINH { get; set; }
        public Nullable<decimal> UMREZ { get; set; }
        public Nullable<decimal> UMREN { get; set; }
    
        public virtual ZAIDM_EX_MATERIAL ZAIDM_EX_MATERIAL { get; set; }
    }
}
