//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENGETAHUI
    {
        public int MENGETAHUI_ID { get; set; }
        public string MENGETAHUI_CODE { get; set; }
        public string MENGETAHUI_DESC { get; set; }
    }
}
