//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTH_CLOSING
    {
        public long MONTH_CLOSING_ID { get; set; }
        public string PLANT_ID { get; set; }
        public Nullable<System.DateTime> CLOSING_DATE { get; set; }
        public string MONTH_FLAG { get; set; }
    
        public virtual T001W T001W { get; set; }
    }
}
