//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBCK1_QUOTA
    {
        public long PBCK1_QUOTA_ID { get; set; }
        public int PBCK1_ID { get; set; }
        public long CK5_ID { get; set; }
        public Sampoerna.EMS.Core.Enums.CK5TransType CK5_TRANS_TYPE { get; set; }
        public decimal CK5_GRAND_TOTAL_EX { get; set; }
        public decimal PBCK1_QTY_APPROVED { get; set; }
        public decimal PREV_REMAINING_QUOTA { get; set; }
        public decimal RECEIVED_AMOUNT { get; set; }
        public decimal TOTAL_REMAINING_QUOTA { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    
        public virtual CK5 CK5 { get; set; }
        public virtual PBCK1 PBCK1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
