//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBCK3_CK5_ITEM
    {
        public long PBCK3_CK5_ITEM_ID { get; set; }
        public long PBCK3_CK5_ID { get; set; }
        public long BRAND_ID { get; set; }
        public decimal REQUEST_QTY { get; set; }
        public decimal APPROVED_QTY { get; set; }
    
        public virtual PBCK3_CK5 PBCK3_CK5 { get; set; }
        public virtual ZAIDM_EX_BRAND ZAIDM_EX_BRAND { get; set; }
    }
}
