//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBCK1_PROD_CONVERTER
    {
        public long PBCK1_PROD_COV_ID { get; set; }
        public Nullable<long> PBCK1_ID { get; set; }
        public Nullable<int> PROD_TYPE_ID { get; set; }
        public Nullable<decimal> CONVERTER_OUTPUT { get; set; }
        public Nullable<int> CONVERTER_UOM_ID { get; set; }
    
        public virtual PBCK1 PBCK1 { get; set; }
        public virtual PBCK1 PBCK11 { get; set; }
        public virtual UOM UOM { get; set; }
    }
}
