//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBCK3_7
    {
        public PBCK3_7()
        {
            this.PBCK3_7_ITEM = new HashSet<PBCK3_7_ITEM>();
        }
    
        public long PBCK3_7_ID { get; set; }
        public string PBCK7_TYPE { get; set; }
        public string PBCK7_NUMBER { get; set; }
        public string PBCK3_NUMBER { get; set; }
        public Nullable<int> DOCUMENT_TYPE_ID { get; set; }
        public Nullable<long> NPPBKC_ID { get; set; }
        public Nullable<long> PLANT_ID { get; set; }
        public Nullable<int> LAMPIRAN { get; set; }
        public Nullable<System.DateTime> EXEC_DATE_FROM { get; set; }
        public Nullable<System.DateTime> EXEC_DATE_TO { get; set; }
        public Nullable<System.DateTime> REPORTING_DATE { get; set; }
        public Nullable<long> BACK1_ID { get; set; }
        public Nullable<long> CK3_ID { get; set; }
        public Nullable<long> CK2_ID { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public Nullable<int> STATUS_PBCK7 { get; set; }
        public Nullable<int> STATUS_PBCK3 { get; set; }
    
        public virtual CK2 CK2 { get; set; }
        public virtual CK3 CK3 { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual ICollection<PBCK3_7_ITEM> PBCK3_7_ITEM { get; set; }
        public virtual USER USER2 { get; set; }
        public virtual ZAIDM_EX_POA ZAIDM_EX_POA { get; set; }
        public virtual ZAIDM_EX_NPPBKC ZAIDM_EX_NPPBKC { get; set; }
        public virtual T1001W T1001W { get; set; }
    }
}
