//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANT_RECEIVE_MATERIAL
    {
        public long PLANT_MATERIAL_ID { get; set; }
        public long PLANT_ID { get; set; }
        public int GOODTYPE_ID { get; set; }
    
        public virtual T1001W T1001W { get; set; }
        public virtual ZAIDM_EX_GOODTYP ZAIDM_EX_GOODTYP { get; set; }
    }
}
