//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class POA
    {
        public POA()
        {
            this.POA_MAP = new HashSet<POA_MAP>();
            this.POA_SK = new HashSet<POA_SK>();
        }
    
        public string POA_ID { get; set; }
        public string ID_CARD { get; set; }
        public string POA_PHONE { get; set; }
        public string POA_ADDRESS { get; set; }
        public string POA_EMAIL { get; set; }
        public string PRINTED_NAME { get; set; }
        public string TITLE { get; set; }
        public string LOGIN_AS { get; set; }
        public string MANAGER_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual ICollection<POA_MAP> POA_MAP { get; set; }
        public virtual ICollection<POA_SK> POA_SK { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual USER USER2 { get; set; }
        public virtual USER USER3 { get; set; }
    }
}
