//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINT_HISTORY
    {
        public long PRINT_HISTORY_ID { get; set; }
        public Sampoerna.EMS.Core.Enums.FormType FORM_TYPE_ID { get; set; }
        public long FORM_ID { get; set; }
        public string FORM_NUMBER { get; set; }
        public System.DateTime PRINT_DATE { get; set; }
        public string PRINT_BY { get; set; }
        public long PRINT_HOSTORY_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
