//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_TYPE
    {
        public PROCESS_TYPE()
        {
            this.CK5 = new HashSet<CK5>();
        }
    
        public int PROTYPE_ID { get; set; }
        public string PROTYPE_NAME { get; set; }
    
        public virtual ICollection<CK5> CK5 { get; set; }
    }
}
