//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENCANA_PRODUKSI
    {
        public long RENCANA_PROD_ID { get; set; }
        public Nullable<long> PBCK1_ID { get; set; }
        public int PRODTYP_ID { get; set; }
        public Nullable<decimal> CONVERTED_OUTPUT { get; set; }
        public Nullable<int> CONVERTED_UOM { get; set; }
    
        public virtual PBCK1 PBCK1 { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual ZAIDM_EX_PRODTYP ZAIDM_EX_PRODTYP { get; set; }
    }
}
