//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_TYPE
    {
        public int REQUEST_TYPE_ID { get; set; }
        public string REQUEST_TYPE_NAME { get; set; }
        public Nullable<int> REQUEST_TYPE_PARENT { get; set; }
    }
}
