//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS
    {
        public STATUS()
        {
            this.CK5 = new HashSet<CK5>();
            this.PBCK1 = new HashSet<PBCK1>();
            this.PBCK3_7 = new HashSet<PBCK3_7>();
            this.PBCK3_71 = new HashSet<PBCK3_7>();
            this.PBCK3_CK5 = new HashSet<PBCK3_CK5>();
            this.PBCK4 = new HashSet<PBCK4>();
        }
    
        public int STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
    
        public virtual ICollection<CK5> CK5 { get; set; }
        public virtual ICollection<PBCK1> PBCK1 { get; set; }
        public virtual ICollection<PBCK3_7> PBCK3_7 { get; set; }
        public virtual ICollection<PBCK3_7> PBCK3_71 { get; set; }
        public virtual ICollection<PBCK3_CK5> PBCK3_CK5 { get; set; }
        public virtual ICollection<PBCK4> PBCK4 { get; set; }
    }
}
