//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_GOV
    {
        public STATUS_GOV()
        {
            this.BACK1 = new HashSet<BACK1>();
            this.BACK3_CK2 = new HashSet<BACK3_CK2>();
            this.PBCK1 = new HashSet<PBCK1>();
            this.PBCK4 = new HashSet<PBCK4>();
        }
    
        public long STATUS_GOV_ID { get; set; }
        public string STATUS_GOV_NAME { get; set; }
    
        public virtual ICollection<BACK1> BACK1 { get; set; }
        public virtual ICollection<BACK3_CK2> BACK3_CK2 { get; set; }
        public virtual ICollection<PBCK1> PBCK1 { get; set; }
        public virtual ICollection<PBCK4> PBCK4 { get; set; }
    }
}
