//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1001W
    {
        public T1001W()
        {
            this.ZAIDM_POA_MAP = new HashSet<ZAIDM_POA_MAP>();
        }
    
        public long PLANT_ID { get; set; }
        public string WERKS { get; set; }
        public string NAME1 { get; set; }
        public string ORT01 { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual ICollection<ZAIDM_POA_MAP> ZAIDM_POA_MAP { get; set; }
    }
}
