//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1001
    {
        public T1001()
        {
            this.T1001K = new HashSet<T1001K>();
        }
    
        public long COMPANY_ID { get; set; }
        public string BUKRS { get; set; }
        public string BUKRSTXT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual ICollection<T1001K> T1001K { get; set; }
    }
}
