//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_BROLE
    {
        public USER_BROLE()
        {
            this.BROLE_MAP = new HashSet<BROLE_MAP>();
            this.PAGE_MAP = new HashSet<PAGE_MAP>();
        }
    
        public string BROLE { get; set; }
        public string BROLE_DESC { get; set; }
    
        public virtual ICollection<BROLE_MAP> BROLE_MAP { get; set; }
        public virtual ICollection<PAGE_MAP> PAGE_MAP { get; set; }
    }
}
