//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PLANT_MAP
    {
        public int USER_PLANT_MAP_ID { get; set; }
        public string USER_ID { get; set; }
        public string PLANT_ID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string NPPBKC_ID { get; set; }
    
        public virtual T001W T001W { get; set; }
        public virtual USER USER { get; set; }
        public virtual ZAIDM_EX_NPPBKC ZAIDM_EX_NPPBKC { get; set; }
    }
}
