//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WASTE
    {
        public string COMPANY_CODE { get; set; }
        public string WERKS { get; set; }
        public string FA_CODE { get; set; }
        public string BRAND_DESC { get; set; }
        public Nullable<decimal> MARKER_REJECT_STICK_QTY { get; set; }
        public Nullable<decimal> PACKER_REJECT_STICK_QTY { get; set; }
        public System.DateTime WASTE_PROD_DATE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string PLANT_NAME { get; set; }
        public Nullable<decimal> DUST_WASTE_GRAM_QTY { get; set; }
        public Nullable<decimal> FLOOR_WASTE_GRAM_QTY { get; set; }
        public Nullable<decimal> DUST_WASTE_STICK_QTY { get; set; }
        public Nullable<decimal> FLOOR_WASTE_STICK_QTY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
