//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_HISTORY
    {
        public long WORKFLOW_HISTORY_ID { get; set; }
        public Nullable<int> FORM_TYPE { get; set; }
        public string ACTION { get; set; }
        public Nullable<int> ACTION_BY { get; set; }
        public Nullable<System.DateTime> ACTION_DATE { get; set; }
        public string FORM_NUMBER { get; set; }
        public string COMMENT { get; set; }
    
        public virtual FORM_TYPE FORM_TYPE1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
