//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_STATE_USERS
    {
        public long WF_STATE_USER_ID { get; set; }
        public long WORKFLOW_STATE_ID { get; set; }
        public string USER_ID { get; set; }
    
        public virtual WORKFLOW_STATE WORKFLOW_STATE { get; set; }
        public virtual USER USER { get; set; }
    }
}
