//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKFLOW_STATE
    {
        public WORKFLOW_STATE()
        {
            this.WORKFLOW_STATE_USERS = new HashSet<WORKFLOW_STATE_USERS>();
        }
    
        public int ACTION_ID { get; set; }
        public string ACTION_NAME { get; set; }
        public Nullable<long> FORM_ID { get; set; }
        public Nullable<int> EMAIL_TEMPLATE_ID { get; set; }
    
        public virtual EMAIL_TEMPLATE EMAIL_TEMPLATE { get; set; }
        public virtual ICollection<WORKFLOW_STATE_USERS> WORKFLOW_STATE_USERS { get; set; }
    }
}
