//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class XML_LOGS_DETAILS
    {
        public long XML_LOGS_DETAILS_ID { get; set; }
        public long XML_LOGS_ID { get; set; }
        public string XML_FILENAME { get; set; }
        public string LOGS { get; set; }
        public Nullable<System.DateTime> ERROR_TIME { get; set; }
    
        public virtual XML_LOGS XML_LOGS { get; set; }
    }
}
