//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAAP_SHIFT_RPT
    {
        public string COMPANY_CODE { get; set; }
        public string WERKS { get; set; }
        public string FA_CODE { get; set; }
        public string UOM { get; set; }
        public System.DateTime PRODUCTION_DATE { get; set; }
        public string BATCH { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<int> BUNDLE { get; set; }
        public string MARKET { get; set; }
        public string DOCGMVTER { get; set; }
        public string MATDOC { get; set; }
        public string ORDR { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
        public string SHIFT { get; set; }
        public Nullable<decimal> ORIGINAL_QTY { get; set; }
        public string ORIGINAL_UOM { get; set; }
    }
}
