//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAIDM_EX_GOODTYP
    {
        public ZAIDM_EX_GOODTYP()
        {
            this.CK5 = new HashSet<CK5>();
            this.ZAIDM_EX_BRAND = new HashSet<ZAIDM_EX_BRAND>();
            this.ZAIDM_EX_MATERIAL = new HashSet<ZAIDM_EX_MATERIAL>();
            this.PBCK1 = new HashSet<PBCK1>();
        }
    
        public int GOODTYPE_ID { get; set; }
        public Nullable<int> EXC_GOOD_TYP { get; set; }
        public string EXT_TYP_DESC { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual ICollection<CK5> CK5 { get; set; }
        public virtual NPPBKC_PLANT NPPBKC_PLANT { get; set; }
        public virtual ICollection<ZAIDM_EX_BRAND> ZAIDM_EX_BRAND { get; set; }
        public virtual ICollection<ZAIDM_EX_MATERIAL> ZAIDM_EX_MATERIAL { get; set; }
        public virtual ICollection<PBCK1> PBCK1 { get; set; }
    }
}
