//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAIDM_EX_KPPBC
    {
        public ZAIDM_EX_KPPBC()
        {
            this.CK5 = new HashSet<CK5>();
        }
    
        public long KPPBC_ID { get; set; }
        public string KPPBC_NUMBER { get; set; }
        public string KPPBC_TYPE { get; set; }
        public Nullable<int> MENGETAHUI_ID { get; set; }
        public string CK1_KEP_HEADER { get; set; }
        public string CK1_KEP_FOOTER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
    
        public virtual ICollection<CK5> CK5 { get; set; }
        public virtual MENGETAHUI MENGETAHUI { get; set; }
        public virtual USER USER { get; set; }
    }
}
