//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.BusinessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAIDM_EX_MATERIAL_BALANCE
    {
        public int MATERIAL_BALANCE_ID { get; set; }
        public string MATERIAL_ID { get; set; }
        public string WERKS { get; set; }
        public Nullable<int> PERIOD_YEAR { get; set; }
        public Nullable<int> PERIOD_MONTH { get; set; }
        public Nullable<decimal> OPEN_BALANCE { get; set; }
        public Nullable<decimal> CLOSE_BALANCE { get; set; }
        public string LGORT { get; set; }
    
        public virtual ZAIDM_EX_MATERIAL ZAIDM_EX_MATERIAL { get; set; }
    }
}
