USE [EMS_QAS]
GO

/****** Object:  Table [dbo].[POA_EXCISER]    Script Date: 6/21/2017 1:44:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[POA_EXCISER](
	[EXCISER_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[POA_ID] [nvarchar](50) NOT NULL,
	[IS_ACTIVE_EXCISER] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EXCISER_ID] ASC,
	[POA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[POA_EXCISER]  WITH CHECK ADD FOREIGN KEY([POA_ID])
REFERENCES [dbo].[POA] ([POA_ID])
GO

