DECLARE @PageId int, 
@Brole nvarchar(10);

SELECT @PageId = PAGE_ID FROM [PAGE] WHERE PAGE_NAME = 'LOGIN';

DECLARE BroleCursor CURSOR FOR
SELECT BROLE FROM USER_BROLE

OPEN BroleCursor

FETCH NEXT FROM BroleCursor 
INTO @Brole;

BEGIN TRANSACTION

BEGIN TRY

WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO PAGE_MAP(PAGE_ID,BROLE)
	VALUES(@PageId,@Brole);
           
	FETCH NEXT FROM BroleCursor 
	INTO @Brole;
END

COMMIT TRANSACTION ;
END TRY
BEGIN CATCH
  ROLLBACK TRANSACTION
END CATCH  

CLOSE BroleCursor;
DEALLOCATE BroleCursor;