/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ZAIDM_EX_MATERIAL SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.ZAIDM_EX_MATERIAL_BALANCE
	(
	MATERIAL_BALANCE_ID int NOT NULL IDENTITY (1, 1),
	MATERIAL_ID nvarchar(18) NULL,
	WERKS nvarchar(4) NULL,
	PERIOD_YEAR int NULL,
	PERIOD_MONTH int NULL,
	OPEN_BALANCE decimal(18, 4) NULL,
	CLOSE_BALANCE decimal(18, 4) NULL,
	LGORT nvarchar(10) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ZAIDM_EX_MATERIAL_BALANCE ADD CONSTRAINT
	PK_ZAIDM_EX_MATERIAL_BALANCE_2 PRIMARY KEY CLUSTERED 
	(
	MATERIAL_BALANCE_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ZAIDM_EX_MATERIAL_BALANCE ADD CONSTRAINT
	FK_ZAIDM_EX_MATERIAL_BALANCE_ZAIDM_EX_MATERIAL FOREIGN KEY
	(
	MATERIAL_ID,
	WERKS
	) REFERENCES dbo.ZAIDM_EX_MATERIAL
	(
	STICKER_CODE,
	WERKS
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ZAIDM_EX_MATERIAL_BALANCE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
