/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ZAAP_SHIFT_RPT SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.REVERSAL
	(
	REVERSAL_ID bigint NOT NULL IDENTITY (1, 1),
	ZAAP_SHIFT_RPT_ID bigint NULL,
	PRODUCTION_DATE datetime NULL,
	FA_CODE nvarchar(18) NULL,
	WERKS nvarchar(4) NULL,
	REVERSAL_QTY decimal(18, 3) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.REVERSAL ADD CONSTRAINT
	PK_REVERSAL_2 PRIMARY KEY CLUSTERED 
	(
	REVERSAL_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.REVERSAL ADD CONSTRAINT
	FK_REVERSAL_ZAAP_SHIFT_RPT FOREIGN KEY
	(
	ZAAP_SHIFT_RPT_ID
	) REFERENCES dbo.ZAAP_SHIFT_RPT
	(
	ZAAP_SHIFT_RPT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.REVERSAL SET (LOCK_ESCALATION = TABLE)
GO
COMMIT