BEGIN TRANSACTION
GO
ALTER TABLE dbo.POA_DELEGATION
	DROP CONSTRAINT FK_POA_DELEGATION_POA
GO
ALTER TABLE dbo.POA_DELEGATION
	DROP CONSTRAINT FK_POA_DELEGATION_POA1
GO
ALTER TABLE dbo.POA SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.[USER] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.POA_DELEGATION ADD CONSTRAINT
	FK_POA_DELEGATION_POAUSER FOREIGN KEY
	(
	POA_FROM
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.POA_DELEGATION ADD CONSTRAINT
	FK_POA_DELEGATION_POAUSER11 FOREIGN KEY
	(
	POA_TO
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.POA_DELEGATION SET (LOCK_ESCALATION = TABLE)
GO
COMMIT