CREATE TABLE [dbo].[POA_DELEGATION](
	[POA_DELEGATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[POA_FROM] [nvarchar](50) NOT NULL,
	[POA_TO] [nvarchar](50) NOT NULL,
	[DATE_FROM] [datetime] NOT NULL,
	[DATE_TO] [datetime] NOT NULL,
	[REASON] [nvarchar](255) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](50) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[POA_DELEGATION]  WITH CHECK ADD  CONSTRAINT [FK_POA_DELEGATION_POA] FOREIGN KEY([POA_FROM])
REFERENCES [dbo].[POA] ([POA_ID])
GO

ALTER TABLE [dbo].[POA_DELEGATION] CHECK CONSTRAINT [FK_POA_DELEGATION_POA]
GO

ALTER TABLE [dbo].[POA_DELEGATION]  WITH CHECK ADD  CONSTRAINT [FK_POA_DELEGATION_POA1] FOREIGN KEY([POA_TO])
REFERENCES [dbo].[POA] ([POA_ID])
GO

ALTER TABLE [dbo].[POA_DELEGATION] CHECK CONSTRAINT [FK_POA_DELEGATION_POA1]
GO

ALTER TABLE [dbo].[POA_DELEGATION]  WITH CHECK ADD  CONSTRAINT [FK_POA_DELEGATION_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[POA_DELEGATION] CHECK CONSTRAINT [FK_POA_DELEGATION_USER]
GO

ALTER TABLE [dbo].[POA_DELEGATION]  WITH CHECK ADD  CONSTRAINT [FK_POA_DELEGATION_USER1] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[POA_DELEGATION] CHECK CONSTRAINT [FK_POA_DELEGATION_USER1]
GO


