IF OBJECT_ID('dbo.GOOD_PROD_TYPE_MAPPING', 'U') IS NOT NULL
  DROP TABLE dbo.GOOD_PROD_TYPE_MAPPING; 

CREATE TABLE [dbo].[GOOD_PROD_TYPE](
	[EXC_GOOD_TYP] [nvarchar](2) NOT NULL,
	[PROD_CODE] [nvarchar](2) NOT NULL,
 CONSTRAINT [PK_GOOD_PROD_TYPE] PRIMARY KEY CLUSTERED 
(
	[EXC_GOOD_TYP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
