
CREATE TABLE [dbo].[GOOD_PROD_TYPE_MAPPING](
	[GOOD_PROD_MAPPING_ID] [int] IDENTITY(1,1) NOT NULL,
	[EX_GOOD_TYPE] [nvarchar](2) NOT NULL,
	[PROD_CODE] [nvarchar](2) NOT NULL,
 CONSTRAINT [PK_GOOD_PROD_TYPE_MAPPING] PRIMARY KEY CLUSTERED 
(
	[GOOD_PROD_MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[GOOD_PROD_TYPE_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_GOOD_PROD_TYPE_MAPPING_ZAIDM_EX_GOODTYP] FOREIGN KEY([EX_GOOD_TYPE])
REFERENCES [dbo].[ZAIDM_EX_GOODTYP] ([EXC_GOOD_TYP])
GO

ALTER TABLE [dbo].[GOOD_PROD_TYPE_MAPPING] CHECK CONSTRAINT [FK_GOOD_PROD_TYPE_MAPPING_ZAIDM_EX_GOODTYP]
GO

ALTER TABLE [dbo].[GOOD_PROD_TYPE_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_GOOD_PROD_TYPE_MAPPING_ZAIDM_EX_PRODTYP] FOREIGN KEY([PROD_CODE])
REFERENCES [dbo].[ZAIDM_EX_PRODTYP] ([PROD_CODE])
GO

ALTER TABLE [dbo].[GOOD_PROD_TYPE_MAPPING] CHECK CONSTRAINT [FK_GOOD_PROD_TYPE_MAPPING_ZAIDM_EX_PRODTYP]
GO
