
CREATE TABLE [dbo].[LACK1_TRACKING_ALCOHOL](
	[LACK1_TRACKING_ALCOHOL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LACK1_ID] [int] NOT NULL,
	[INVENTORY_MOVEMENT_ID] [bigint] NOT NULL,
	[IS_FIRST_LEVEL] [bit] NOT NULL,
	[IS_FINAL_GOODS] [bit] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_LACK1_TRACKING_ALCOHOL] PRIMARY KEY CLUSTERED 
(
	[LACK1_TRACKING_ALCOHOL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK1_TRACKING_ALCOHOL]  WITH CHECK ADD  CONSTRAINT [FK_LACK1_TRACKING_ALCOHOL_INVENTORY_MOVEMENT] FOREIGN KEY([INVENTORY_MOVEMENT_ID])
REFERENCES [dbo].[INVENTORY_MOVEMENT] ([INVENTORY_MOVEMENT_ID])
GO

ALTER TABLE [dbo].[LACK1_TRACKING_ALCOHOL] CHECK CONSTRAINT [FK_LACK1_TRACKING_ALCOHOL_INVENTORY_MOVEMENT]
GO

ALTER TABLE [dbo].[LACK1_TRACKING_ALCOHOL]  WITH CHECK ADD  CONSTRAINT [FK_LACK1_TRACKING_ALCOHOL_LACK1] FOREIGN KEY([LACK1_ID])
REFERENCES [dbo].[LACK1] ([LACK1_ID])
GO

ALTER TABLE [dbo].[LACK1_TRACKING_ALCOHOL] CHECK CONSTRAINT [FK_LACK1_TRACKING_ALCOHOL_LACK1]
GO
