/****** Object:  Table [dbo].[XML_LOGS]    Script Date: 12/18/2015 3:22:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XML_LOGS](
	[XML_LOGS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[XML_FILENAME] [varchar](50) NOT NULL,
	[LAST_ERROR_TIME] [datetime] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NULL,
	[MODIFIED_DATE] [timestamp] NULL,
	[STATUS] [int] NOT NULL,
 CONSTRAINT [PK_XML_LOGS] PRIMARY KEY CLUSTERED 
(
	[XML_LOGS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_XML_LOGS] UNIQUE NONCLUSTERED 
(
	[XML_FILENAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[XML_LOGS_DETAILS]    Script Date: 12/18/2015 3:22:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[XML_LOGS_DETAILS](
	[XML_LOGS_DETAILS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[XML_LOGS_ID] [bigint] NOT NULL,
	[XML_FILENAME] [varchar](50) NOT NULL,
	[LOGS] [varchar](max) NULL,
	[ERROR_TIME] [datetime] NULL,
 CONSTRAINT [PK_XML_LOGS_DETAILS] PRIMARY KEY CLUSTERED 
(
	[XML_LOGS_DETAILS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[XML_LOGS_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_XML_LOGS_DETAILS_XML_LOGS] FOREIGN KEY([XML_LOGS_ID])
REFERENCES [dbo].[XML_LOGS] ([XML_LOGS_ID])
GO
ALTER TABLE [dbo].[XML_LOGS_DETAILS] CHECK CONSTRAINT [FK_XML_LOGS_DETAILS_XML_LOGS]
GO
