BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_XML_LOGS
	(
	XML_LOGS_ID bigint NOT NULL IDENTITY (1, 1),
	XML_FILENAME varchar(50) NOT NULL,
	LAST_ERROR_TIME datetime NOT NULL,
	CREATED_BY varchar(50) NOT NULL,
	CREATED_DATE datetime NOT NULL,
	MODIFIED_BY varchar(50) NULL,
	MODIFIED_DATE datetime NULL,
	STATUS int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_XML_LOGS SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_XML_LOGS ON
GO
IF EXISTS(SELECT * FROM dbo.XML_LOGS)
	 EXEC('INSERT INTO dbo.Tmp_XML_LOGS (XML_LOGS_ID, XML_FILENAME, LAST_ERROR_TIME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, STATUS)
		SELECT XML_LOGS_ID, XML_FILENAME, LAST_ERROR_TIME, CREATED_BY, CREATED_DATE, MODIFIED_BY, CONVERT(datetime, MODIFIED_DATE), STATUS FROM dbo.XML_LOGS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_XML_LOGS OFF
GO
ALTER TABLE dbo.XML_LOGS_DETAILS
	DROP CONSTRAINT FK_XML_LOGS_DETAILS_XML_LOGS
GO
DROP TABLE dbo.XML_LOGS
GO
EXECUTE sp_rename N'dbo.Tmp_XML_LOGS', N'XML_LOGS', 'OBJECT' 
GO
ALTER TABLE dbo.XML_LOGS ADD CONSTRAINT
	PK_XML_LOGS PRIMARY KEY CLUSTERED 
	(
	XML_LOGS_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.XML_LOGS ADD CONSTRAINT
	IX_XML_LOGS UNIQUE NONCLUSTERED 
	(
	XML_FILENAME
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE dbo.XML_LOGS_DETAILS ADD CONSTRAINT
	FK_XML_LOGS_DETAILS_XML_LOGS FOREIGN KEY
	(
	XML_LOGS_ID
	) REFERENCES dbo.XML_LOGS
	(
	XML_LOGS_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.XML_LOGS_DETAILS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
