
/****** Object:  Table [dbo].[BLOCK_STOCK]    Script Date: 9/7/2015 3:09:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BLOCK_STOCK](
	[BLOCK_STOCK_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[MATERIAL_ID] [nvarchar](18) NOT NULL,
	[PLANT] [nvarchar](4) NOT NULL,
	[BLOCKED] [decimal](18, 2) NULL,
	[BUN] [nvarchar](5) NULL,
 CONSTRAINT [PK_BLOCK_STOCK] PRIMARY KEY CLUSTERED 
(
	[BLOCK_STOCK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


