
CREATE TABLE dbo.Tmp_PRODUCTION
	(
	COMPANY_CODE nvarchar(4) NOT NULL,
	WERKS nvarchar(4) NOT NULL,
	FA_CODE nvarchar(18) NOT NULL,
	BRAND_DESC nvarchar(200) NULL,
	QTY_UNPACKED decimal(18, 2) NULL,
	QTY_PACKED decimal(18, 2) NULL,
	UOM nvarchar(5) NULL,
	PRODUCTION_DATE datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PRODUCTION SET (LOCK_ESCALATION = TABLE)
GO
IF EXISTS(SELECT * FROM dbo.PRODUCTION)
	 EXEC('INSERT INTO dbo.Tmp_PRODUCTION (COMPANY_CODE, WERKS, FA_CODE, BRAND_DESC, QTY_UNPACKED, QTY_PACKED, UOM, PRODUCTION_DATE)
		SELECT COMPANY_CODE, WERKS, FA_CODE, BRAND_DESC, QTY_UNPACKED, QTY_PACKED, UOM, PRODUCTION_DATE FROM dbo.PRODUCTION WITH (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.PRODUCTION
GO
EXECUTE sp_rename N'dbo.Tmp_PRODUCTION', N'PRODUCTION', 'OBJECT' 
GO
ALTER TABLE dbo.PRODUCTION ADD CONSTRAINT
	PK_PRODUCTION PRIMARY KEY CLUSTERED 
	(
	COMPANY_CODE,
	WERKS,
	FA_CODE,
	PRODUCTION_DATE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

