ALTER TABLE dbo.LACK1_PRODUCTION_DETAIL ADD CONSTRAINT
	FK_LACK1_PRODUCTION_DETAIL_UOM FOREIGN KEY
	(
	UOM_ID
	) REFERENCES dbo.UOM
	(
	UOM_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.LACK1_PRODUCTION_DETAIL SET (LOCK_ESCALATION = TABLE)
GO