BEGIN TRANSACTION

ALTER TABLE LACK1_PRODUCTION_DETAIL
ADD FA_CODE nvarchar(18) NULL;

ALTER TABLE LACK1_PRODUCTION_DETAIL
ADD BRAND_DESC nvarchar(200) NULL;

ALTER TABLE LACK1_PRODUCTION_DETAIL
ADD ORDR nvarchar(10) NULL;

COMMIT TRANSACTION
