USE [EMS-DEV2]
GO

/****** Object:  Table [dbo].[CK4C_DECREE_DOC]    Script Date: 9/14/2015 9:13:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CK4C_DECREE_DOC](
	[CK4C_DECREE_DOC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CK4C_ID] [int] NOT NULL,
	[FILE_NAME] [nvarchar](50) NOT NULL,
	[FILE_PATH] [nvarchar](250) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CK4C_DECREE_DOC] PRIMARY KEY CLUSTERED 
(
	[CK4C_DECREE_DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CK4C_DECREE_DOC]  WITH CHECK ADD  CONSTRAINT [FK_CK4C_DECREE_DOC_CK4C] FOREIGN KEY([CK4C_ID])
REFERENCES [dbo].[CK4C] ([CK4C_ID])
GO

ALTER TABLE [dbo].[CK4C_DECREE_DOC] CHECK CONSTRAINT [FK_CK4C_DECREE_DOC_CK4C]
GO

ALTER TABLE [dbo].[CK4C_DECREE_DOC]  WITH CHECK ADD  CONSTRAINT [FK_CK4C_DECREE_DOC_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[CK4C_DECREE_DOC] CHECK CONSTRAINT [FK_CK4C_DECREE_DOC_USER]
GO


