ALTER TABLE LACK2
ADD APPROVED_BY_MANAGER NVARCHAR(50) NULL
GO
ALTER TABLE LACK2
ADD REJECTED_BY NVARCHAR(50) NULL
GO
ALTER TABLE LACK2
ADD REJECTED_DATE DATETIME NULL
GO
ALTER TABLE LACK2
ADD APPROVED_BY_MANAGER_DATE DATETIME NULL
GO
