update PBCK4
set CK3_OFFICE_VALUE = null

ALTER TABLE dbo.PBCK4
	DROP CONSTRAINT FK_PBCK4_USER
GO
ALTER TABLE dbo.PBCK4
	DROP CONSTRAINT FK_PBCK4_USER_MODIFIED
GO
ALTER TABLE dbo.PBCK4
	DROP CONSTRAINT FK_PBCK4_USER_REJECT
GO
ALTER TABLE dbo.PBCK4
	DROP CONSTRAINT FK_PBCK4_USER1
GO
ALTER TABLE dbo.[USER] SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.PBCK4
	DROP CONSTRAINT FK_PBCK4_POA
GO
ALTER TABLE dbo.POA SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE dbo.Tmp_PBCK4
	(
	PBCK4_ID int NOT NULL IDENTITY (1, 1),
	PBCK4_NUMBER varchar(50) NOT NULL,
	PLANT_ID nvarchar(4) NULL,
	PLANT_NAME nvarchar(30) NULL,
	NPPBKC_ID nvarchar(15) NOT NULL,
	NPPBKC_DESCRIPTION nvarchar(50) NULL,
	COMPANY_ID nvarchar(4) NULL,
	COMPANY_NAME nvarchar(35) NULL,
	STATUS int NOT NULL,
	GOV_STATUS int NULL,
	REPORTED_ON date NULL,
	BACK1_NO nvarchar(35) NULL,
	BACK1_DATE datetime NULL,
	CK3_NO nvarchar(35) NULL,
	CK3_DATE datetime NULL,
	CK3_OFFICE_VALUE decimal(18, 2) NULL,
	CREATED_BY nvarchar(50) NOT NULL,
	CREATED_DATE datetime NOT NULL,
	MODIFIED_BY nvarchar(50) NULL,
	MODIFIED_DATE datetime NULL,
	APPROVED_BY_POA nvarchar(50) NULL,
	APPROVED_BY_POA_DATE datetime NULL,
	REJECTED_BY nvarchar(50) NULL,
	REJECTED_DATE datetime NULL,
	APPROVED_BY_MANAGER nvarchar(50) NULL,
	APPROVED_BY_MANAGER_DATE datetime NULL,
	POA_PRINTED_NAME nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PBCK4 SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_PBCK4 ON
GO
IF EXISTS(SELECT * FROM dbo.PBCK4)
	 EXEC('INSERT INTO dbo.Tmp_PBCK4 (PBCK4_ID, PBCK4_NUMBER, PLANT_ID, PLANT_NAME, NPPBKC_ID, NPPBKC_DESCRIPTION, COMPANY_ID, COMPANY_NAME, STATUS, GOV_STATUS, REPORTED_ON, BACK1_NO, BACK1_DATE, CK3_NO, CK3_DATE, CK3_OFFICE_VALUE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, APPROVED_BY_POA, APPROVED_BY_POA_DATE, REJECTED_BY, REJECTED_DATE, APPROVED_BY_MANAGER, APPROVED_BY_MANAGER_DATE, POA_PRINTED_NAME)
		SELECT PBCK4_ID, PBCK4_NUMBER, PLANT_ID, PLANT_NAME, NPPBKC_ID, NPPBKC_DESCRIPTION, COMPANY_ID, COMPANY_NAME, STATUS, GOV_STATUS, REPORTED_ON, BACK1_NO, BACK1_DATE, CK3_NO, CK3_DATE, CONVERT(decimal(18, 2), CK3_OFFICE_VALUE), CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, APPROVED_BY_POA, APPROVED_BY_POA_DATE, REJECTED_BY, REJECTED_DATE, APPROVED_BY_MANAGER, APPROVED_BY_MANAGER_DATE, POA_PRINTED_NAME FROM dbo.PBCK4 WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_PBCK4 OFF
GO
ALTER TABLE dbo.PBCK4_ITEM
	DROP CONSTRAINT FK_PBCK4_ITEM_PBCK4
GO
ALTER TABLE dbo.PBCK4_DOCUMENT
	DROP CONSTRAINT FK_PBCK4_DOCUMENT_PBCK4
GO
DROP TABLE dbo.PBCK4
GO
EXECUTE sp_rename N'dbo.Tmp_PBCK4', N'PBCK4', 'OBJECT' 
GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	PK_PBCK4 PRIMARY KEY CLUSTERED 
	(
	PBCK4_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	FK_PBCK4_POA FOREIGN KEY
	(
	APPROVED_BY_POA
	) REFERENCES dbo.POA
	(
	POA_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	FK_PBCK4_USER FOREIGN KEY
	(
	CREATED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	FK_PBCK4_USER_MODIFIED FOREIGN KEY
	(
	MODIFIED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	FK_PBCK4_USER_REJECT FOREIGN KEY
	(
	REJECTED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4 ADD CONSTRAINT
	FK_PBCK4_USER1 FOREIGN KEY
	(
	APPROVED_BY_MANAGER
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.PBCK4_DOCUMENT ADD CONSTRAINT
	FK_PBCK4_DOCUMENT_PBCK4 FOREIGN KEY
	(
	PBCK4_ID
	) REFERENCES dbo.PBCK4
	(
	PBCK4_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4_DOCUMENT SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.PBCK4_ITEM ADD CONSTRAINT
	FK_PBCK4_ITEM_PBCK4 FOREIGN KEY
	(
	PBCK4_ID
	) REFERENCES dbo.PBCK4
	(
	PBCK4_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK4_ITEM SET (LOCK_ESCALATION = TABLE)
GO

