
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.PBCK1.APPROVED_BY', N'Tmp_APPROVED_BY', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.PBCK1.Tmp_APPROVED_BY', N'APPROVED_BY_POA', 'COLUMN' 
GO

EXECUTE sp_rename N'dbo.PBCK1.APPROVED_DATE', N'Tmp_APPROVED_DATE', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.PBCK1.Tmp_APPROVED_DATE', N'APPROVED_DATE_POA', 'COLUMN' 
GO

COMMIT
