ALTER TABLE LACK1
ADD LACK1_UOM_ID nvarchar(5) NULL
GO

UPDATE LACK1
SET LACK1_UOM_ID = 'KG'
GO

ALTER TABLE LACK1
ALTER COLUMN LACK1_UOM_ID nvarchar(5) NOT NULL
GO

ALTER TABLE dbo.LACK1 ADD CONSTRAINT
	FK_LACK1_UOM FOREIGN KEY
	(
	LACK1_UOM_ID
	) REFERENCES dbo.UOM
	(
	UOM_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO