EXECUTE sp_rename N'dbo.CK4C.APPROVED_BY', N'Tmp_APPROVED_BY_POA', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.CK4C.APPROVED_DATE', N'Tmp_APPROVED_DATE_POA_1', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.CK4C.Tmp_APPROVED_BY_POA', N'APPROVED_BY_POA', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.CK4C.Tmp_APPROVED_DATE_POA_1', N'APPROVED_DATE_POA', 'COLUMN' 
GO
ALTER TABLE dbo.CK4C SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE CK4C
ADD APPROVED_BY_MANAGER nvarchar(50) null,
	APPROVED_DATE_MANAGER datetime null
GO
