ALTER TABLE dbo.CK5_MATERIAL
	DROP CONSTRAINT FK_CK5_MATERIAL_CK5
GO
ALTER TABLE dbo.CK5 SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE dbo.Tmp_CK5_MATERIAL
	(
	CK5_MATERIAL_ID bigint NOT NULL IDENTITY (1, 1),
	CK5_ID bigint NULL,
	MATERIAL_ID bigint NULL,
	LINE_ITEM int NULL,
	QTY numeric(18, 0) NULL,
	CONVERTED_QTY numeric(18, 2) NULL,
	CONVERTED_UOM_ID int NULL,
	BRAND varchar(50) NULL,
	PLANT_ID nvarchar(4) NULL,
	UOM varchar(50) NULL,
	CONVERTION numeric(18, 3) NULL,
	HJE numeric(18, 2) NULL,
	TARIFF numeric(18, 2) NULL,
	EXCISE_VALUE numeric(18, 2) NULL,
	USD_VALUE numeric(18, 2) NULL,
	NOTE varchar(100) NULL,
	CONVERTED_UOM varchar(50) NULL,
	MATERIAL_DESC nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_CK5_MATERIAL SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_CK5_MATERIAL ON
GO
IF EXISTS(SELECT * FROM dbo.CK5_MATERIAL)
	 EXEC('INSERT INTO dbo.Tmp_CK5_MATERIAL (CK5_MATERIAL_ID, CK5_ID, MATERIAL_ID, LINE_ITEM, QTY, CONVERTED_QTY, CONVERTED_UOM_ID, BRAND, PLANT_ID, UOM, CONVERTION, HJE, TARIFF, EXCISE_VALUE, USD_VALUE, NOTE, CONVERTED_UOM, MATERIAL_DESC)
		SELECT CK5_MATERIAL_ID, CK5_ID, MATERIAL_ID, LINE_ITEM, QTY, CONVERTED_QTY, CONVERTED_UOM_ID, BRAND, PLANT_ID, UOM, CONVERTION, HJE, TARIFF, EXCISE_VALUE, USD_VALUE, NOTE, CONVERTED_UOM, MATERIAL_DESC FROM dbo.CK5_MATERIAL WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_CK5_MATERIAL OFF
GO
DROP TABLE dbo.CK5_MATERIAL
GO
EXECUTE sp_rename N'dbo.Tmp_CK5_MATERIAL', N'CK5_MATERIAL', 'OBJECT' 
GO
ALTER TABLE dbo.CK5_MATERIAL ADD CONSTRAINT
	PK_CK5_MATERIAL PRIMARY KEY CLUSTERED 
	(
	CK5_MATERIAL_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.CK5_MATERIAL ADD CONSTRAINT
	FK_CK5_MATERIAL_CK5 FOREIGN KEY
	(
	CK5_ID
	) REFERENCES dbo.CK5
	(
	CK5_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

