BEGIN TRANSACTION
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
	DROP CONSTRAINT FK_ZAIDM_EX_BRAND_ZAIDM_EX_PCODE
GO
ALTER TABLE dbo.ZAIDM_EX_PCODE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
