ALTER TABLE PBCK7
ADD PLANT_NAME NVARCHAR(35) NULL
GO
ALTER TABLE PBCK7
ADD PLANT_CITY NVARCHAR(35) NULL
GO
ALTER TABLE PBCK7
ADD GOV_STATUS INT NULL
GO
ALTER TABLE PBCK7
ADD STATUS INT NOT NULL
GO