ALTER TABLE PBCK1
ADD SUPPLIER_PORT_NAME nvarchar(50) NULL;

ALTER TABLE PBCK1
ADD SUPPLIER_NPPBKC_ID nvarchar(15) NULL;

ALTER TABLE PBCK1
ADD SUPPLIER_KPPBC_ID nvarchar(10) NULL;

ALTER TABLE PBCK1
ADD SUPPLIER_PLANT_WERKS nvarchar(4) NULL;