use [EMS];

GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_T001W_MODIFIED_BY_USER]') AND parent_object_id = OBJECT_ID(N'[dbo].[T001W]'))
ALTER TABLE [dbo].[T001W] DROP CONSTRAINT [FK_T001W_MODIFIED_BY_USER]
GO


GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_T001_MODIFIED_BY_USER]') AND parent_object_id = OBJECT_ID(N'[dbo].[T001]'))
ALTER TABLE [dbo].[T001] DROP CONSTRAINT [FK_T001_MODIFIED_BY_USER]
GO


IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ZAIDM_EX_NPPBKC_MODIFIED_DATE_USER]') AND parent_object_id = OBJECT_ID(N'[dbo].[ZAIDM_EX_NPPBKC]'))
ALTER TABLE [dbo].[ZAIDM_EX_NPPBKC] DROP CONSTRAINT [FK_ZAIDM_EX_NPPBKC_MODIFIED_DATE_USER]
GO

ALTER TABLE [dbo].[ZAIDM_EX_NPPBKC]
ADD CREATED_BY NVARCHAR(50) NULL




