ALTER TABLE T1001W
DROP CONSTRAINT FK_T1001W_ZAIDM_EX_GOODTYP

ALTER TABLE T1001W
drop column RECEIVED_MATERIAL_TYPE_ID

USE [EMS]
GO

/****** Object:  Table [dbo].[PLANT_RECEIVE_MATERIAL]    Script Date: 01/07/2015 11:04:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLANT_RECEIVE_MATERIAL](
	[PLANT_MATERIAL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PLANT_ID] [bigint] NOT NULL,
	[GOODTYPE_ID] [int] NOT NULL,
 CONSTRAINT [PK_PLANT_RECEIVE_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[PLANT_MATERIAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PLANT_RECEIVE_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_PLANT_RECEIVE_MATERIAL_T1001W] FOREIGN KEY([PLANT_ID])
REFERENCES [dbo].[T1001W] ([PLANT_ID])
GO

ALTER TABLE [dbo].[PLANT_RECEIVE_MATERIAL] CHECK CONSTRAINT [FK_PLANT_RECEIVE_MATERIAL_T1001W]
GO

ALTER TABLE [dbo].[PLANT_RECEIVE_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_PLANT_RECEIVE_MATERIAL_ZAIDM_EX_GOODTYP] FOREIGN KEY([GOODTYPE_ID])
REFERENCES [dbo].[ZAIDM_EX_GOODTYP] ([GOODTYPE_ID])
GO

ALTER TABLE [dbo].[PLANT_RECEIVE_MATERIAL] CHECK CONSTRAINT [FK_PLANT_RECEIVE_MATERIAL_ZAIDM_EX_GOODTYP]
GO


