BEGIN TRANSACTION
GO
CREATE TABLE dbo.PRINT_HISTORY
	(
	PRINT_HOSTORY_ID bigint NOT NULL IDENTITY (1, 1),
	FORM_TYPE_ID int NOT NULL,
	FORM_ID bigint NOT NULL,
	FORM_NUMBER nvarchar(30) NULL,
	PRINT_DATE datetime NOT NULL,
	PRINT_BY nvarchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PRINT_HISTORY ADD CONSTRAINT
	PK_Table_1_1 PRIMARY KEY CLUSTERED 
	(
	PRINT_HOSTORY_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PRINT_HISTORY ADD CONSTRAINT
	FK_PRINT_HISTORY_USER FOREIGN KEY
	(
	PRINT_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PRINT_HISTORY SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
