BEGIN TRANSACTION
GO
ALTER TABLE dbo.CK5 ADD CONSTRAINT
	FK_CK5_USER FOREIGN KEY
	(
	APPROVED_BY_MANAGER
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CK5 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
