
GO
ALTER TABLE [dbo].[PBCK7_ITEM] DROP CONSTRAINT [FK_PBCK7_ITEM_PBCK7]
GO
ALTER TABLE [dbo].[PBCK7] DROP CONSTRAINT [FK_PBCK7_USER]
GO
ALTER TABLE [dbo].[PBCK7] DROP CONSTRAINT [FK_PBCK7_REJECTED_USER]
GO
ALTER TABLE [dbo].[PBCK7] DROP CONSTRAINT [FK_PBCK7_POA]
GO
ALTER TABLE [dbo].[PBCK7] DROP CONSTRAINT [FK_PBCK7_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK7] DROP CONSTRAINT [FK_PBCK7_MANAGER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7_ITEM] DROP CONSTRAINT [FK_PBCK3_PBCK7_ITEM_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] DROP CONSTRAINT [FK_PBCK3_PBCK7_USER1]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] DROP CONSTRAINT [FK_PBCK3_PBCK7_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] DROP CONSTRAINT [FK_PBCK3_PBCK7_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] DROP CONSTRAINT [FK_PBCK3_PBCK7_CREATED_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] DROP CONSTRAINT [FK_PBCK3_PBCK7_APPROVED_USER]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_USER]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_REJECT]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_POA]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK3] DROP CONSTRAINT [FK_PBCK3_MANAGER]
GO
ALTER TABLE [dbo].[CK2_DOCUMENT] DROP CONSTRAINT [FK_CK2_DOCUMENT_CK2]
GO
ALTER TABLE [dbo].[CK2] DROP CONSTRAINT [FK_CK2_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[BACK3_DOCUMENT] DROP CONSTRAINT [FK_BACK3_DOCUMENT_BACK3]
GO
ALTER TABLE [dbo].[BACK3] DROP CONSTRAINT [FK_BACK3_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[BACK1_DOCUMENT] DROP CONSTRAINT [FK_BACK1_DOCUMENT_BACK1]
GO
ALTER TABLE [dbo].[BACK1] DROP CONSTRAINT [FK_BACK1_PBCK7]
GO
/****** Object:  Table [dbo].[PBCK7_ITEM]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[PBCK7_ITEM]
GO
/****** Object:  Table [dbo].[PBCK7]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[PBCK7]
GO
/****** Object:  Table [dbo].[PBCK3_PBCK7_ITEM]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[PBCK3_PBCK7_ITEM]
GO
/****** Object:  Table [dbo].[PBCK3_PBCK7]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[PBCK3_PBCK7]
GO
/****** Object:  Table [dbo].[PBCK3]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[PBCK3]
GO
/****** Object:  Table [dbo].[CK2_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[CK2_DOCUMENT]
GO
/****** Object:  Table [dbo].[CK2]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[CK2]
GO
/****** Object:  Table [dbo].[BACK3_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[BACK3_DOCUMENT]
GO
/****** Object:  Table [dbo].[BACK3]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[BACK3]
GO
/****** Object:  Table [dbo].[BACK1_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[BACK1_DOCUMENT]
GO
/****** Object:  Table [dbo].[BACK1]    Script Date: 9/17/2015 10:48:03 AM ******/
DROP TABLE [dbo].[BACK1]
GO
/****** Object:  Table [dbo].[BACK1]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BACK1](
	[BACK1_ID] [int] IDENTITY(1,1) NOT NULL,
	[BACK1_NUMBER] [nvarchar](30) NOT NULL,
	[BACK1_DATE] [datetime] NOT NULL,
	[PBCK7_ID] [int] NOT NULL,
 CONSTRAINT [PK_BACK1] PRIMARY KEY CLUSTERED 
(
	[BACK1_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BACK1_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BACK1_DOCUMENT](
	[BACK1_DOCUMENT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BACK1] [int] NOT NULL,
	[FILE_NAME] [nvarchar](50) NOT NULL,
	[FILE_PATH] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_BACK1_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[BACK1_DOCUMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BACK3]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BACK3](
	[BACK3_ID] [int] IDENTITY(1,1) NOT NULL,
	[BACK3_NUMBER] [nvarchar](35) NULL,
	[BACK3_DATE] [date] NULL,
	[PBCK3_PBCK7_ID] [int] NOT NULL,
 CONSTRAINT [PK_BACK3] PRIMARY KEY CLUSTERED 
(
	[BACK3_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BACK3_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BACK3_DOCUMENT](
	[BACK3_DOC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FILE_PATH] [nvarchar](250) NOT NULL,
	[FILE_NAME] [nvarchar](150) NULL,
	[BACK3_ID] [int] NOT NULL,
 CONSTRAINT [PK_BACK3_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[BACK3_DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CK2]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CK2](
	[CK2_ID] [int] IDENTITY(1,1) NOT NULL,
	[CK2_NUMBER] [nvarchar](35) NULL,
	[CK2_DATE] [date] NULL,
	[CK2_VALUE] [decimal](15, 2) NULL,
	[PBCK3_PBCK7_ID] [int] NOT NULL,
 CONSTRAINT [PK_CK2] PRIMARY KEY CLUSTERED 
(
	[CK2_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CK2_DOCUMENT]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CK2_DOCUMENT](
	[CK2_DOC_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FILE_PATH] [nvarchar](250) NULL,
	[FILE_NAME] [nvarchar](150) NULL,
	[CK2_ID] [int] NOT NULL,
 CONSTRAINT [PK_CK2_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[CK2_DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBCK3]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBCK3](
	[PBCK3_ID] [int] IDENTITY(1,1) NOT NULL,
	[PBCK3_NUMBER] [nvarchar](35) NOT NULL,
	[PBCK3_DATE] [date] NOT NULL,
	[PBCK7_ID] [int] NOT NULL,
	[GOV_STATUS] [int] NULL,
	[STATUS] [int] NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[APPROVED_BY_MANAGER] [nvarchar](50) NULL,
	[APPROVED_BY_MANAGER_DATE] [datetime] NULL,
	[REJECTED_BY] [nvarchar](50) NULL,
	[REJECTED_DATE] [datetime] NULL,
 CONSTRAINT [PK_PBCK3] PRIMARY KEY CLUSTERED 
(
	[PBCK3_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBCK3_PBCK7]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBCK3_PBCK7](
	[PBCK3_PBCK7_ID] [int] IDENTITY(1,1) NOT NULL,
	[PBCK7_NUMBER] [nvarchar](30) NOT NULL,
	[PBCK3_NUMBER] [nvarchar](30) NULL,
	[PBCK7_STATUS] [int] NOT NULL,
	[PBCK3_STATUS] [int] NULL,
	[PBCK7_DATE] [datetime] NOT NULL,
	[PBCK3_DATE] [datetime] NULL,
	[DOC_TYPE] [int] NOT NULL,
	[NPPBCK_ID] [nvarchar](15) NULL,
	[PLANT_ID] [nvarchar](4) NULL,
	[PLANT_NAME] [nvarchar](30) NULL,
	[PLANT_CITY] [nvarchar](25) NULL,
	[EXEC_DATE_FROM] [datetime] NULL,
	[EXEC_DATE_TO] [datetime] NULL,
	[GOV_STATUS] [int] NULL,
	[STATUS] [int] NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[APPROVED_BY_MANAGER] [nvarchar](50) NULL,
	[APPROVED_BY_MANAGER_DATE] [datetime] NULL,
	[REJECTED_BY] [nvarchar](50) NULL,
	[REJECTED_DATE] [datetime] NULL,
 CONSTRAINT [PK_PBCK3_PBCK7] PRIMARY KEY CLUSTERED 
(
	[PBCK3_PBCK7_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBCK3_PBCK7_ITEM]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBCK3_PBCK7_ITEM](
	[PBCK3_PBCK7_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PBCK3_PBCK7_ID] [int] NOT NULL,
	[FA_CODE] [nvarchar](18) NULL,
	[PRODUCT_ALIAS] [nvarchar](50) NULL,
	[BRAND_CE] [nvarchar](65) NULL,
	[BRAND_CONTENT] [decimal](15, 2) NULL,
	[PBCK7_QTY] [decimal](15, 2) NULL,
	[BACK1_QTY] [decimal](15, 2) NULL,
	[SERIES_VALUE] [decimal](15, 2) NULL,
	[HJE] [decimal](15, 2) NULL,
	[TARIFF] [decimal](15, 2) NULL,
	[FISCAL_YEAR] [int] NULL,
	[EXCISE_VALUE] [decimal](15, 2) NULL,
 CONSTRAINT [PK_PBCK3_PBCK7_ITEM] PRIMARY KEY CLUSTERED 
(
	[PBCK3_PBCK7_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBCK7]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBCK7](
	[PBCK7_ID] [int] IDENTITY(1,1) NOT NULL,
	[PBCK7_NUMBER] [nvarchar](35) NOT NULL,
	[PBCK7_DATE] [date] NOT NULL,
	[DOCUMENT_TYPE] [int] NOT NULL,
	[NPPBKC] [nvarchar](15) NOT NULL,
	[PLANT_ID] [nvarchar](4) NOT NULL,
	[EXEC_DATE_FROM] [date] NOT NULL,
	[EXEC_DATE_TO] [date] NOT NULL,
	[LAMPIRAN] [nvarchar](50) NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[APPROVED_BY_MANAGER] [nvarchar](50) NULL,
	[APPROVED_BY_MANAGER_DATE] [datetime] NULL,
	[REJECTED_BY] [nvarchar](50) NULL,
	[REJECTED_DATE] [datetime] NULL,
	[PLANT_NAME] [nvarchar](35) NULL,
	[PLANT_CITY] [nvarchar](35) NULL,
	[GOV_STATUS] [int] NULL,
	[STATUS] [int] NOT NULL,
 CONSTRAINT [PK_PBCK7_NUMBER] PRIMARY KEY CLUSTERED 
(
	[PBCK7_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PBCK7_ITEM]    Script Date: 9/17/2015 10:48:03 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PBCK7_ITEM](
	[PBCK7_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PBCK7_ID] [int] NOT NULL,
	[FA_CODE] [nvarchar](18) NULL,
	[PRODUCT_ALIAS] [nvarchar](50) NULL,
	[BRAND_CE] [nvarchar](65) NULL,
	[BRAND_CONTENT] [decimal](15, 2) NULL,
	[PBCK7_QTY] [decimal](15, 2) NULL,
	[BACK1_QTY] [decimal](15, 2) NULL,
	[SERIES_VALUE] [decimal](15, 2) NULL,
	[HJE] [decimal](15, 2) NULL,
	[TARIFF] [decimal](15, 2) NULL,
	[FISCAL_YEAR] [int] NULL,
	[EXCISE_VALUE] [decimal](15, 2) NULL,
 CONSTRAINT [PK_PBCK7_ITEM] PRIMARY KEY CLUSTERED 
(
	[PBCK7_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[BACK1]  WITH CHECK ADD  CONSTRAINT [FK_BACK1_PBCK7] FOREIGN KEY([PBCK7_ID])
REFERENCES [dbo].[PBCK7] ([PBCK7_ID])
GO
ALTER TABLE [dbo].[BACK1] CHECK CONSTRAINT [FK_BACK1_PBCK7]
GO
ALTER TABLE [dbo].[BACK1_DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FK_BACK1_DOCUMENT_BACK1] FOREIGN KEY([BACK1])
REFERENCES [dbo].[BACK1] ([BACK1_ID])
GO
ALTER TABLE [dbo].[BACK1_DOCUMENT] CHECK CONSTRAINT [FK_BACK1_DOCUMENT_BACK1]
GO
ALTER TABLE [dbo].[BACK3]  WITH CHECK ADD  CONSTRAINT [FK_BACK3_PBCK3_PBCK7] FOREIGN KEY([PBCK3_PBCK7_ID])
REFERENCES [dbo].[PBCK3_PBCK7] ([PBCK3_PBCK7_ID])
GO
ALTER TABLE [dbo].[BACK3] CHECK CONSTRAINT [FK_BACK3_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[BACK3_DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FK_BACK3_DOCUMENT_BACK3] FOREIGN KEY([BACK3_ID])
REFERENCES [dbo].[BACK3] ([BACK3_ID])
GO
ALTER TABLE [dbo].[BACK3_DOCUMENT] CHECK CONSTRAINT [FK_BACK3_DOCUMENT_BACK3]
GO
ALTER TABLE [dbo].[CK2]  WITH CHECK ADD  CONSTRAINT [FK_CK2_PBCK3_PBCK7] FOREIGN KEY([PBCK3_PBCK7_ID])
REFERENCES [dbo].[PBCK3_PBCK7] ([PBCK3_PBCK7_ID])
GO
ALTER TABLE [dbo].[CK2] CHECK CONSTRAINT [FK_CK2_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[CK2_DOCUMENT]  WITH CHECK ADD  CONSTRAINT [FK_CK2_DOCUMENT_CK2] FOREIGN KEY([CK2_ID])
REFERENCES [dbo].[CK2] ([CK2_ID])
GO
ALTER TABLE [dbo].[CK2_DOCUMENT] CHECK CONSTRAINT [FK_CK2_DOCUMENT_CK2]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_MANAGER] FOREIGN KEY([APPROVED_BY_MANAGER])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_MANAGER]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_MODIFIED_USER] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7] FOREIGN KEY([PBCK7_ID])
REFERENCES [dbo].[PBCK7] ([PBCK7_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_POA] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[POA] ([POA_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_POA]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_REJECT] FOREIGN KEY([REJECTED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_REJECT]
GO
ALTER TABLE [dbo].[PBCK3]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3] CHECK CONSTRAINT [FK_PBCK3_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_APPROVED_USER] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] CHECK CONSTRAINT [FK_PBCK3_PBCK7_APPROVED_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_CREATED_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] CHECK CONSTRAINT [FK_PBCK3_PBCK7_CREATED_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_MODIFIED_USER] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] CHECK CONSTRAINT [FK_PBCK3_PBCK7_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_USER] FOREIGN KEY([APPROVED_BY_MANAGER])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] CHECK CONSTRAINT [FK_PBCK3_PBCK7_USER]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_USER1] FOREIGN KEY([REJECTED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7] CHECK CONSTRAINT [FK_PBCK3_PBCK7_USER1]
GO
ALTER TABLE [dbo].[PBCK3_PBCK7_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_PBCK3_PBCK7_ITEM_PBCK3_PBCK7] FOREIGN KEY([PBCK3_PBCK7_ID])
REFERENCES [dbo].[PBCK3_PBCK7] ([PBCK3_PBCK7_ID])
GO
ALTER TABLE [dbo].[PBCK3_PBCK7_ITEM] CHECK CONSTRAINT [FK_PBCK3_PBCK7_ITEM_PBCK3_PBCK7]
GO
ALTER TABLE [dbo].[PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_MANAGER] FOREIGN KEY([APPROVED_BY_MANAGER])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK7] CHECK CONSTRAINT [FK_PBCK7_MANAGER]
GO
ALTER TABLE [dbo].[PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_MODIFIED_USER] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK7] CHECK CONSTRAINT [FK_PBCK7_MODIFIED_USER]
GO
ALTER TABLE [dbo].[PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_POA] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[POA] ([POA_ID])
GO
ALTER TABLE [dbo].[PBCK7] CHECK CONSTRAINT [FK_PBCK7_POA]
GO
ALTER TABLE [dbo].[PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_REJECTED_USER] FOREIGN KEY([REJECTED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK7] CHECK CONSTRAINT [FK_PBCK7_REJECTED_USER]
GO
ALTER TABLE [dbo].[PBCK7]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[PBCK7] CHECK CONSTRAINT [FK_PBCK7_USER]
GO
ALTER TABLE [dbo].[PBCK7_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_ITEM_PBCK7] FOREIGN KEY([PBCK7_ID])
REFERENCES [dbo].[PBCK7] ([PBCK7_ID])
GO
ALTER TABLE [dbo].[PBCK7_ITEM] CHECK CONSTRAINT [FK_PBCK7_ITEM_PBCK7]
GO
