USE [EMS-DEV2]
GO

/****** Object:  Table [dbo].[LACK2_ITEM]    Script Date: 8/21/2015 1:04:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK2_ITEM](
	[LACK2_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LACK2_ID] [int] NOT NULL,
	[CK5_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_LACK2_ITEM] PRIMARY KEY CLUSTERED 
(
	[LACK2_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK2_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_ITEM_CK5] FOREIGN KEY([CK5_ID])
REFERENCES [dbo].[CK5] ([CK5_ID])
GO

ALTER TABLE [dbo].[LACK2_ITEM] CHECK CONSTRAINT [FK_LACK2_ITEM_CK5]
GO

ALTER TABLE [dbo].[LACK2_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_ITEM_LACK2] FOREIGN KEY([LACK2_ID])
REFERENCES [dbo].[LACK2] ([LACK2_ID])
GO

ALTER TABLE [dbo].[LACK2_ITEM] CHECK CONSTRAINT [FK_LACK2_ITEM_LACK2]
GO


