DROP TABLE PAGE_MAP
GO

ALTER TABLE [USER]
DROP CONSTRAINT FK_USER_USER_GROUP

ALTER TABLE [USER]
DROP COLUMN USER_GROUP_ID
GO

DROP TABLE USER_GROUP
GO



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BROLE_MAP](
 [BROLE_MAP_ID] [int] IDENTITY(1,1) NOT NULL,
 [BROLE] [nvarchar](10) NOT NULL,
 [MSACCT] [nvarchar](50) NOT NULL,
 [START_DATE] [datetime] NULL,
 [END_DATE] [datetime] NULL,
 CONSTRAINT [PK_BROLE_MAP] PRIMARY KEY CLUSTERED 
(
 [BROLE_MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[PAGE_MAP](
 [PAGE_MAP_ID] [int] IDENTITY(1,1) NOT NULL,
 [PAGE_ID] [int] NOT NULL,
 [BROLE] [nvarchar](10) NULL,
 CONSTRAINT [PK_PAGE_MAP] PRIMARY KEY CLUSTERED 
(
 [PAGE_MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_BROLE](
 [BROLE] [nvarchar](10) NOT NULL,
 [BROLE_DESC] [nvarchar](100) NULL,
 CONSTRAINT [PK_USER_BROLE] PRIMARY KEY CLUSTERED 
(
 [BROLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_USER_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[BROLE_MAP]  WITH CHECK ADD  CONSTRAINT [FK_BROLE_MAP_USER] FOREIGN KEY([MSACCT])
REFERENCES [dbo].[USER] ([USER_ID])
GO
ALTER TABLE [dbo].[BROLE_MAP] CHECK CONSTRAINT [FK_BROLE_MAP_USER]
GO
ALTER TABLE [dbo].[BROLE_MAP]  WITH CHECK ADD  CONSTRAINT [FK_BROLE_MAP_USER_BROLE] FOREIGN KEY([BROLE])
REFERENCES [dbo].[USER_BROLE] ([BROLE])
GO
ALTER TABLE [dbo].[BROLE_MAP] CHECK CONSTRAINT [FK_BROLE_MAP_USER_BROLE]
GO
ALTER TABLE [dbo].[PAGE_MAP]  WITH CHECK ADD  CONSTRAINT [FK_PAGE_MAP_PAGE] FOREIGN KEY([PAGE_ID])
REFERENCES [dbo].[PAGE] ([PAGE_ID])
GO
ALTER TABLE [dbo].[PAGE_MAP] CHECK CONSTRAINT [FK_PAGE_MAP_PAGE]
GO
ALTER TABLE [dbo].[PAGE_MAP]  WITH CHECK ADD  CONSTRAINT [FK_PAGE_MAP_USER_BROLE] FOREIGN KEY([BROLE])
REFERENCES [dbo].[USER_BROLE] ([BROLE])
GO
ALTER TABLE [dbo].[PAGE_MAP] CHECK CONSTRAINT [FK_PAGE_MAP_USER_BROLE]
GO