
EXECUTE sp_rename N'dbo.PBCK1.SUPPLIER_KPPBC_ID', N'Tmp_SUPPLIER_KPPBC_NAME', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.PBCK1.Tmp_SUPPLIER_KPPBC_NAME', N'SUPPLIER_KPPBC_NAME', 'COLUMN' 
GO
ALTER TABLE dbo.PBCK1 ADD
	SUPPLIER_KPPBC_ID nvarchar(10) NULL
GO
ALTER TABLE dbo.PBCK1 SET (LOCK_ESCALATION = TABLE)
GO