USE [EMS-DEV2]
GO

/****** Object:  Table [dbo].[LACK2]    Script Date: 8/21/2015 12:59:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK2](
	[LACK2_ID] [int] IDENTITY(1,1) NOT NULL,
	[BUKRS] [nvarchar](4) NOT NULL,
	[BUTXT] [nvarchar](35) NOT NULL,
	[PERIOD_MONTH] [int] NOT NULL,
	[PERIOD_YEAR] [int] NOT NULL,
	[LEVEL_PLANT_ID] [nvarchar](4) NOT NULL,
	[LEVEL_PLANT_NAME] [nvarchar](30) NOT NULL,
	[LEVEL_PLANT_CITY] [nvarchar](25) NULL,
	[SUBMISSION_DATE] [datetime] NOT NULL,
	[EX_GOOD_TYP] [nvarchar](2) NOT NULL,
	[EX_TYP_DESC] [nvarchar](65) NOT NULL,
	[GOV_STATUS] [int] NOT NULL,
	[STATUS] [int] NOT NULL,
	[DECREE_DATE] [datetime] NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
 CONSTRAINT [PK_LACK2] PRIMARY KEY CLUSTERED 
(
	[LACK2_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK2]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_MONTH] FOREIGN KEY([PERIOD_MONTH])
REFERENCES [dbo].[MONTH] ([MONTH_ID])
GO

ALTER TABLE [dbo].[LACK2] CHECK CONSTRAINT [FK_LACK2_MONTH]
GO

ALTER TABLE [dbo].[LACK2]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_USER_APPROVED_BY] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK2] CHECK CONSTRAINT [FK_LACK2_USER_APPROVED_BY]
GO

ALTER TABLE [dbo].[LACK2]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_USER_CREATED_BY] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK2] CHECK CONSTRAINT [FK_LACK2_USER_CREATED_BY]
GO

ALTER TABLE [dbo].[LACK2]  WITH CHECK ADD  CONSTRAINT [FK_LACK2_USER_MODIFIED_BY] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[LACK2] CHECK CONSTRAINT [FK_LACK2_USER_MODIFIED_BY]
GO


