delete from EX_GROUP_TYPE_DETAILS;
delete from EX_GROUP_TYPE;

DBCC CHECKIDENT ('[EX_GROUP_TYPE]', RESEED, 0);

INSERT INTO EX_GROUP_TYPE(GROUP_NAME) VALUES('Etil Alkohol');
INSERT INTO EX_GROUP_TYPE(GROUP_NAME) VALUES('MMEA');
INSERT INTO EX_GROUP_TYPE(GROUP_NAME) VALUES('Hasil Tembakau');
INSERT INTO EX_GROUP_TYPE(GROUP_NAME) VALUES('Lainnya');