/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK3_PBCK7
	DROP CONSTRAINT FK_PBCK3_PBCK7_APPROVED_USER
GO
ALTER TABLE dbo.PBCK3_PBCK7
	DROP CONSTRAINT FK_PBCK3_PBCK7_CREATED_USER
GO
ALTER TABLE dbo.PBCK3_PBCK7
	DROP CONSTRAINT FK_PBCK3_PBCK7_MODIFIED_USER
GO
ALTER TABLE dbo.[USER] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_PBCK3_PBCK7
	(
	PBCK3_PBCK7_ID int NOT NULL IDENTITY (1, 1),
	PBCK7_NUMBER nvarchar(30) NOT NULL,
	PBCK3_NUMBER nvarchar(30) NULL,
	PBCK7_STATUS int NOT NULL,
	PBCK3_STATUS int NULL,
	PBCK7_DATE datetime NOT NULL,
	PBCK3_DATE datetime NULL,
	DOC_TYPE int NOT NULL,
	NPPBCK_ID nvarchar(15) NULL,
	PLANT_ID nvarchar(4) NULL,
	PLANT_NAME nvarchar(30) NULL,
	PLANT_CITY nvarchar(25) NULL,
	EXEC_DATE_FROM datetime NULL,
	EXEC_DATE_TO datetime NULL,
	GOV_STATUS int NOT NULL,
	STATUS int NOT NULL,
	APPROVED_BY nvarchar(50) NULL,
	APPROVED_DATE datetime NULL,
	CREATED_BY nvarchar(50) NOT NULL,
	CREATED_DATE datetime NOT NULL,
	MODIFIED_BY nvarchar(50) NULL,
	MODIFIED_DATE datetime NULL,
	APPROVED_BY_MANAGER nvarchar(50) NULL,
	APPROVED_BY_MANAGER_DATE datetime NULL,
	REJECTED_BY nvarchar(50) NULL,
	REJECTED_DATE datetime NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_PBCK3_PBCK7 SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_PBCK3_PBCK7 ON
GO
IF EXISTS(SELECT * FROM dbo.PBCK3_PBCK7)
	 EXEC('INSERT INTO dbo.Tmp_PBCK3_PBCK7 (PBCK3_PBCK7_ID, PBCK7_NUMBER, PBCK3_NUMBER, PBCK7_STATUS, PBCK3_STATUS, PBCK7_DATE, PBCK3_DATE, DOC_TYPE, NPPBCK_ID, PLANT_ID, PLANT_NAME, PLANT_CITY, EXEC_DATE_FROM, EXEC_DATE_TO, GOV_STATUS, STATUS, APPROVED_BY, APPROVED_DATE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE)
		SELECT PBCK3_PBCK7_ID, PBCK7_NUMBER, PBCK3_NUMBER, PBCK7_STATUS, PBCK3_STATUS, PBCK7_DATE, PBCK3_DATE, DOC_TYPE, NPPBCK_ID, PLANT_ID, PLANT_NAME, PLANT_CITY, EXEC_DATE_FROM, EXEC_DATE_TO, GOV_STATUS, STATUS, APPROVED_BY, APPROVED_DATE, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE FROM dbo.PBCK3_PBCK7 WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_PBCK3_PBCK7 OFF
GO
ALTER TABLE dbo.BACK1
	DROP CONSTRAINT FK_BACK1_PBCK3_PBCK7
GO
ALTER TABLE dbo.PBCK3_PBCK7_ITEM
	DROP CONSTRAINT FK_PBCK3_PBCK7_ITEM_PBCK3_PBCK7
GO
ALTER TABLE dbo.CK2
	DROP CONSTRAINT FK_CK2_PBCK3_PBCK7
GO
ALTER TABLE dbo.BACK3
	DROP CONSTRAINT FK_BACK3_PBCK3_PBCK7
GO
DROP TABLE dbo.PBCK3_PBCK7
GO
EXECUTE sp_rename N'dbo.Tmp_PBCK3_PBCK7', N'PBCK3_PBCK7', 'OBJECT' 
GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	PK_PBCK3_PBCK7 PRIMARY KEY CLUSTERED 
	(
	PBCK3_PBCK7_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	FK_PBCK3_PBCK7_APPROVED_USER FOREIGN KEY
	(
	APPROVED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	FK_PBCK3_PBCK7_CREATED_USER FOREIGN KEY
	(
	CREATED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	FK_PBCK3_PBCK7_MODIFIED_USER FOREIGN KEY
	(
	MODIFIED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	FK_PBCK3_PBCK7_USER FOREIGN KEY
	(
	APPROVED_BY_MANAGER
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK3_PBCK7 ADD CONSTRAINT
	FK_PBCK3_PBCK7_USER1 FOREIGN KEY
	(
	REJECTED_BY
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BACK3 ADD CONSTRAINT
	FK_BACK3_PBCK3_PBCK7 FOREIGN KEY
	(
	PBCK3_PBCK7_ID
	) REFERENCES dbo.PBCK3_PBCK7
	(
	PBCK3_PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BACK3 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CK2 ADD CONSTRAINT
	FK_CK2_PBCK3_PBCK7 FOREIGN KEY
	(
	PBCK3_PBCK7_ID
	) REFERENCES dbo.PBCK3_PBCK7
	(
	PBCK3_PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CK2 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK3_PBCK7_ITEM ADD CONSTRAINT
	FK_PBCK3_PBCK7_ITEM_PBCK3_PBCK7 FOREIGN KEY
	(
	PBCK3_PBCK7_ID
	) REFERENCES dbo.PBCK3_PBCK7
	(
	PBCK3_PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK3_PBCK7_ITEM SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	FK_BACK1_PBCK3_PBCK7 FOREIGN KEY
	(
	PBCK3_PBCK7_ID
	) REFERENCES dbo.PBCK3_PBCK7
	(
	PBCK3_PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BACK1 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT