
ALTER TABLE CK5
ALTER COLUMN SUBMISSION_NUMBER NVARCHAR(50) NULL

ALTER TABLE PBCK1
ALTER COLUMN [NUMBER] NVARCHAR(50) NULL

ALTER TABLE LACK1
ALTER COLUMN LACK1_NUMBER NVARCHAR(50) NULL

ALTER TABLE LACK2
ALTER COLUMN LACK2_NUMBER NVARCHAR(50) NULL
