DROP TABLE [LACK1_PBCK1_MAPPING]
GO

/****** Object:  Table [dbo].[LACK1_PBCK1_MAPPING]    Script Date: 9/3/2015 3:03:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LACK1_PBCK1_MAPPING](
	[LACK1_PBCK1_MAPPING_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LACK1_ID] [int] NOT NULL,
	[PBCK1_ID] [int] NOT NULL,
 CONSTRAINT [PK_LACK1_PBCK1_MAPPING] PRIMARY KEY CLUSTERED 
(
	[LACK1_PBCK1_MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LACK1_PBCK1_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_LACK1_PBCK1_MAPPING_LACK1] FOREIGN KEY([LACK1_ID])
REFERENCES [dbo].[LACK1] ([LACK1_ID])
GO

ALTER TABLE [dbo].[LACK1_PBCK1_MAPPING] CHECK CONSTRAINT [FK_LACK1_PBCK1_MAPPING_LACK1]
GO

ALTER TABLE [dbo].[LACK1_PBCK1_MAPPING]  WITH CHECK ADD  CONSTRAINT [FK_LACK1_PBCK1_MAPPING_PBCK1] FOREIGN KEY([PBCK1_ID])
REFERENCES [dbo].[PBCK1] ([PBCK1_ID])
GO

ALTER TABLE [dbo].[LACK1_PBCK1_MAPPING] CHECK CONSTRAINT [FK_LACK1_PBCK1_MAPPING_PBCK1]
GO


