ALTER TABLE PRODUCTION
ADD BATCH NVARCHAR(35) NULL
ALTER TABLE PRODUCTION
ADD PROD_QTY_STICK DECIMAL(15,2) NULL
ALTER TABLE PRODUCTION
ADD QTY DECIMAL(15,2) NULL
ALTER TABLE PRODUCTION
ADD BUNDLE INT NULL
ALTER TABLE PRODUCTION
ADD MARKET  NVARCHAR(2) NULL
ALTER TABLE PRODUCTION
ADD DOCGMVTER  NVARCHAR(35) NULL

