CREATE TABLE dbo.Tmp_WASTE
	(
	COMPANY_CODE nvarchar(4) NOT NULL,
	WERKS nvarchar(4) NOT NULL,
	FA_CODE nvarchar(18) NOT NULL,
	BRAND_DESC nvarchar(200) NULL,
	WASTE_QTY_STICK decimal(18, 2) NULL,
	WASTE_QTY_GRAM decimal(18, 2) NULL,
	REJECT_QTY_STICK decimal(18, 2) NULL,
	WASTE_PROD_DATE datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_WASTE SET (LOCK_ESCALATION = TABLE)
GO
IF EXISTS(SELECT * FROM dbo.WASTE)
	 EXEC('INSERT INTO dbo.Tmp_WASTE (COMPANY_CODE, WERKS, FA_CODE, BRAND_DESC, WASTE_QTY_STICK, WASTE_QTY_GRAM, REJECT_QTY_STICK, WASTE_PROD_DATE)
		SELECT COMPANY_CODE, WERKS, FA_CODE, BRAND_DESC, WASTE_QTY_STICK, WASTE_QTY_GRAM, REJECT_QTY_STICK, WASTE_PROD_DATE FROM dbo.WASTE WITH (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.WASTE
GO
EXECUTE sp_rename N'dbo.Tmp_WASTE', N'WASTE', 'OBJECT' 
GO
ALTER TABLE dbo.WASTE ADD CONSTRAINT
	PK_WASTE PRIMARY KEY CLUSTERED 
	(
	COMPANY_CODE,
	WERKS,
	FA_CODE,
	WASTE_PROD_DATE
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO