EXECUTE sp_rename N'dbo.PBCK4.PBCK1_NUMBER', N'Tmp_PBCK4_NUMBER', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.PBCK4.Tmp_PBCK4_NUMBER', N'PBCK4_NUMBER', 'COLUMN' 
GO

ALTER TABLE PBCK4 ALTER COLUMN PBCK4_NUMBER varchar(50)

