ALTER TABLE dbo.PRODUCTION ADD
	CREATED_DATE datetime NOT NULL CONSTRAINT DF_MyTable_MyColumn DEFAULT '2015-01-01',
	MODIFIED_DATE datetime NULL,
	CREATED_BY nvarchar(50) NULL,
	MODIFIED_BY nvarchar(50) NULL;
	
ALTER TABLE dbo.PRODUCTION
DROP CONSTRAINT DF_MyTable_MyColumn
