CREATE TABLE [dbo].[CK5_FILE_UPLOAD](
	[CK5_FILE_UPLOAD_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CK5_ID] [bigint] NOT NULL,
	[FILE_NAME] [nvarchar](50) NOT NULL,
	[FILE_PATH] [nvarchar](250) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CK5_FILE_UPLOAD] PRIMARY KEY CLUSTERED 
(
	[CK5_FILE_UPLOAD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CK5_FILE_UPLOAD]  WITH CHECK ADD  CONSTRAINT [FK_CK5_FILE_UPLOAD_CK5_FILE_UPLOAD] FOREIGN KEY([CK5_ID])
REFERENCES [dbo].[CK5] ([CK5_ID])
GO

ALTER TABLE [dbo].[CK5_FILE_UPLOAD] CHECK CONSTRAINT [FK_CK5_FILE_UPLOAD_CK5_FILE_UPLOAD]
GO

ALTER TABLE [dbo].[CK5_FILE_UPLOAD]  WITH CHECK ADD  CONSTRAINT [FK_CK5_FILE_UPLOAD_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[CK5_FILE_UPLOAD] CHECK CONSTRAINT [FK_CK5_FILE_UPLOAD_USER]
GO

