ALTER TABLE LACK1_PRODUCTION_DETAIL
ADD UOM_ID nvarchar(5) NULL
GO

UPDATE LACK1_PRODUCTION_DETAIL
SET UOM_ID = 'BTG'
GO

ALTER TABLE LACK1_PRODUCTION_DETAIL
ALTER COLUMN UOM_ID nvarchar(5) NOT NULL
GO