ALTER TABLE dbo.USER_PLANT_MAP ADD CONSTRAINT
			FK_USER_PLANT_MAP_ZAIDM_EX_NPPBKC FOREIGN KEY
			(
			NPPBKC_ID
			) REFERENCES dbo.ZAIDM_EX_NPPBKC
			(
			NPPBKC_ID
			) ON UPDATE  NO ACTION 
			 ON DELETE  NO ACTION 