BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK3 ADD
	EXEC_DATE_FROM date NULL,
	EXEC_DATE_TO date NULL
GO

UPDATE PBCK3
SET EXEC_DATE_FROM = GETDATE(),
EXEC_DATE_TO = GETDATE()
GO

ALTER TABLE dbo.PBCK3 ALTER COLUMN
	EXEC_DATE_FROM date NOT NULL
GO

ALTER TABLE dbo.PBCK3 ALTER COLUMN
	EXEC_DATE_TO date NOT NULL
GO

COMMIT
