/****** Object:  Index [IX_WASTE_STOCK]    Script Date: 11/12/2015 9:47:57 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_WASTE_STOCK] ON [dbo].[WASTE_STOCK]
(
	[STOCK] ASC,
	[WERKS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


