ALTER TABLE [ZAIDM_EX_MATERIAL]
ADD HJE numeric(15,2)
ALTER TABLE [ZAIDM_EX_MATERIAL]
ADD HJE_CURR nvarchar(5)
ALTER TABLE [ZAIDM_EX_MATERIAL]
ADD TARIFF decimal(15,2)
ALTER TABLE [ZAIDM_EX_MATERIAL]
ADD TARIFF_CURR nvarchar(5)