USE [EMS-DEV2]
GO

/****** Object:  Table [dbo].[PBCK3_PBCK7_ITEM]    Script Date: 9/16/2015 11:19:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PBCK7_ITEM](
	[PBCK7_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PBCK7_ID] [int] NOT NULL,
	[FA_CODE] [nvarchar](18) NULL,
	[PRODUCT_ALIAS] [nvarchar](50) NULL,
	[BRAND_CE] [nvarchar](65) NULL,
	[BRAND_CONTENT] [decimal](15, 2) NULL,
	[PBCK7_QTY] [decimal](15, 2) NULL,
	[BACK1_QTY] [decimal](15, 2) NULL,
	[SERIES_VALUE] [decimal](15, 2) NULL,
	[HJE] [decimal](15, 2) NULL,
	[TARIFF] [decimal](15, 2) NULL,
	[FISCAL_YEAR] [int] NULL,
	[EXCISE_VALUE] [decimal](15, 2) NULL,
 CONSTRAINT [PK_PBCK7_ITEM] PRIMARY KEY CLUSTERED 
(
	[PBCK7_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PBCK7_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_PBCK7_ITEM_PBCK7] FOREIGN KEY([PBCK7_ID])
REFERENCES [dbo].[PBCK7] ([PBCK7_ID])
GO

ALTER TABLE [dbo].[PBCK7_ITEM] CHECK CONSTRAINT [FK_PBCK7_ITEM_PBCK7]
GO


