USE [EMS]
GO

DROP TABLE [WORKFLOW_HISTORY]
GO

/****** Object:  Table [dbo].[WORKFLOW_HISTORY]    Script Date: 07/07/2015 13:39:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKFLOW_HISTORY](
	[WORKFLOW_HISTORY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FORM_TYPE_ID] [int] NOT NULL,
	[FORM_ID] [bigint] NOT NULL,
	[FORM_NUMBER] [nvarchar](30) NULL,
	[ACTION] [int] NOT NULL,
	[ACTION_BY] [int] NOT NULL,
	[ACTION_DATE] [datetime] NULL,
	[COMMENT] [nvarchar](50) NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[WORKFLOW_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WORKFLOW_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_WORKFLOW_HISTORY_USER] FOREIGN KEY([ACTION_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[WORKFLOW_HISTORY] CHECK CONSTRAINT [FK_WORKFLOW_HISTORY_USER]
GO


