ALTER TABLE dbo.BACK1 ADD
	CK5_ID bigint NULL
GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	FK_BACK1_CK5 FOREIGN KEY
	(
	CK5_ID
	) REFERENCES dbo.CK5
	(
	CK5_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
