
EXECUTE sp_rename N'dbo.CK4C_ITEM.CK4C_ITEM', N'Tmp_CK4C_ITEM_ID', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.CK4C_ITEM.Tmp_CK4C_ITEM_ID', N'CK4C_ITEM_ID', 'COLUMN' 
GO
ALTER TABLE dbo.CK4C_ITEM SET (LOCK_ESCALATION = TABLE)
GO
