CREATE TABLE [dbo].[WASTE_ROLE](
	[WASTE_ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [nvarchar](50) NOT NULL,
	[GROUP_ROLE] [int] NOT NULL,
	[WERKS] [nvarchar](4) NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [nvarchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
 CONSTRAINT [PK_WASTE_ROLE] PRIMARY KEY CLUSTERED 
(
	[WASTE_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WASTE_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_WASTE_ROLE_T001W] FOREIGN KEY([WERKS])
REFERENCES [dbo].[T001W] ([WERKS])
GO

ALTER TABLE [dbo].[WASTE_ROLE] CHECK CONSTRAINT [FK_WASTE_ROLE_T001W]
GO

ALTER TABLE [dbo].[WASTE_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_WASTE_ROLE_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[WASTE_ROLE] CHECK CONSTRAINT [FK_WASTE_ROLE_USER]
GO

ALTER TABLE [dbo].[WASTE_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_WASTE_ROLE_USER1] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[WASTE_ROLE] CHECK CONSTRAINT [FK_WASTE_ROLE_USER1]
GO

ALTER TABLE [dbo].[WASTE_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_WASTE_ROLE_USER2] FOREIGN KEY([MODIFIED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[WASTE_ROLE] CHECK CONSTRAINT [FK_WASTE_ROLE_USER2]
GO


