BEGIN TRANSACTION
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT FK_ZAIDM_EX_BRAND_ZAIDM_EX_PRODTYP
GO
ALTER TABLE dbo.ZAIDM_EX_PRODTYP SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT FK_ZAIDM_EX_BRAND_ZAIDM_EX_MARKET
GO
ALTER TABLE dbo.ZAIDM_EX_MARKET SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT FK_ZAIDM_EX_BRAND_ZAIDM_EX_GOODTYP
GO
ALTER TABLE dbo.ZAIDM_EX_GOODTYP SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT FK_ZAIDM_EX_BRAND_T001W
GO
ALTER TABLE dbo.T001W SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.ZAIDM_EX_SERIES
 DROP CONSTRAINT DF__ZAIDM_EX___IS_DE__4119A21D
GO
CREATE TABLE dbo.Tmp_ZAIDM_EX_SERIES
 (
 SERIES_CODE nvarchar(4) NOT NULL,
 SERIES_VALUE decimal(15, 2) NULL,
 CREATED_DATE datetime NOT NULL,
 MODIFIED_DATE datetime NULL,
 CREATED_BY nvarchar(50) NULL,
 MODIFIED_BY nvarchar(50) NULL,
 IS_DELETED bit NULL
 )  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_ZAIDM_EX_SERIES SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_ZAIDM_EX_SERIES ADD CONSTRAINT
 DF__ZAIDM_EX___IS_DE__4119A21D DEFAULT ((0)) FOR IS_DELETED
GO
IF EXISTS(SELECT * FROM dbo.ZAIDM_EX_SERIES)
  EXEC('INSERT INTO dbo.Tmp_ZAIDM_EX_SERIES (SERIES_CODE, SERIES_VALUE, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_DELETED)
  SELECT SERIES_CODE, CONVERT(decimal(15, 2), SERIES_VALUE), CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_DELETED FROM dbo.ZAIDM_EX_SERIES WITH (HOLDLOCK TABLOCKX)')
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT FK_ZAIDM_EX_BRAND_ZAIDM_EX_SERIES
GO
DROP TABLE dbo.ZAIDM_EX_SERIES
GO
EXECUTE sp_rename N'dbo.Tmp_ZAIDM_EX_SERIES', N'ZAIDM_EX_SERIES', 'OBJECT' 
GO
ALTER TABLE dbo.ZAIDM_EX_SERIES ADD CONSTRAINT
 PK_ZAIDM_EX_SERIES PRIMARY KEY CLUSTERED 
 (
 SERIES_CODE
 ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT DF_ZAIDM_EX_BRAND_IS_FROM_SAP
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND
 DROP CONSTRAINT DF_ZAIDM_EX_BRAND_IS_DELETED
GO
CREATE TABLE dbo.Tmp_ZAIDM_EX_BRAND
 (
 WERKS nvarchar(4) NOT NULL,
 FA_CODE nvarchar(18) NOT NULL,
 STICKER_CODE nvarchar(18) NULL,
 PER_CODE nvarchar(2) NULL,
 BRAND_CE nvarchar(65) NOT NULL,
 SKEP_NO nvarchar(30) NULL,
 SKEP_DATE datetime NULL,
 PROD_CODE nvarchar(2) NOT NULL,
 SERIES_CODE nvarchar(4) NOT NULL,
 BRAND_CONTENT nvarchar(4) NULL,
 MARKET_ID nvarchar(2) NULL,
 COUNTRY nvarchar(3) NULL,
 HJE_IDR numeric(15, 2) NULL,
 HJE_CURR nvarchar(5) NULL,
 TARIFF numeric(15, 2) NULL,
 TARIF_CURR nvarchar(5) NULL,
 COLOUR nvarchar(70) NULL,
 EXC_GOOD_TYP nvarchar(2) NULL,
 CUT_FILLER_CODE nvarchar(30) NULL,
 PRINTING_PRICE numeric(15, 2) NULL,
 CONVERSION numeric(15, 2) NULL,
 START_DATE datetime NULL,
 END_DATE datetime NULL,
 STATUS bit NULL,
 IS_FROM_SAP bit NULL,
 IS_DELETED bit NULL,
 CREATED_DATE datetime NOT NULL,
 CREATED_BY nvarchar(50) NULL,
 MODIFIED_DATE datetime NULL,
 MODIFIED_BY nvarchar(50) NULL,
 PER_CODE_DESC nvarchar(30) NULL
 )  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_ZAIDM_EX_BRAND SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Tmp_ZAIDM_EX_BRAND ADD CONSTRAINT
 DF_ZAIDM_EX_BRAND_IS_FROM_SAP DEFAULT ((1)) FOR IS_FROM_SAP
GO
ALTER TABLE dbo.Tmp_ZAIDM_EX_BRAND ADD CONSTRAINT
 DF_ZAIDM_EX_BRAND_IS_DELETED DEFAULT ((0)) FOR IS_DELETED
GO
IF EXISTS(SELECT * FROM dbo.ZAIDM_EX_BRAND)
  EXEC('INSERT INTO dbo.Tmp_ZAIDM_EX_BRAND (WERKS, FA_CODE, STICKER_CODE, PER_CODE, BRAND_CE, SKEP_NO, SKEP_DATE, PROD_CODE, SERIES_CODE, BRAND_CONTENT, MARKET_ID, COUNTRY, HJE_IDR, HJE_CURR, TARIFF, TARIF_CURR, COLOUR, EXC_GOOD_TYP, CUT_FILLER_CODE, PRINTING_PRICE, CONVERSION, START_DATE, END_DATE, STATUS, IS_FROM_SAP, IS_DELETED, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, PER_CODE_DESC)
  SELECT WERKS, FA_CODE, STICKER_CODE, PER_CODE, BRAND_CE, SKEP_NO, SKEP_DATE, PROD_CODE, SERIES_CODE, BRAND_CONTENT, MARKET_ID, COUNTRY, HJE_IDR, HJE_CURR, TARIFF, TARIF_CURR, COLOUR, EXC_GOOD_TYP, CUT_FILLER_CODE, PRINTING_PRICE, CONVERSION, START_DATE, END_DATE, STATUS, IS_FROM_SAP, IS_DELETED, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, PER_CODE_DESC FROM dbo.ZAIDM_EX_BRAND WITH (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.ZAIDM_EX_BRAND
GO
EXECUTE sp_rename N'dbo.Tmp_ZAIDM_EX_BRAND', N'ZAIDM_EX_BRAND', 'OBJECT' 
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 PK_ZAIDM_EX_BRAND PRIMARY KEY CLUSTERED 
 (
 WERKS,
 FA_CODE
 ) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 FK_ZAIDM_EX_BRAND_T001W FOREIGN KEY
 (
 WERKS
 ) REFERENCES dbo.T001W
 (
 WERKS
 ) ON UPDATE  NO ACTION 
  ON DELETE  NO ACTION 
 
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 FK_ZAIDM_EX_BRAND_ZAIDM_EX_GOODTYP FOREIGN KEY
 (
 EXC_GOOD_TYP
 ) REFERENCES dbo.ZAIDM_EX_GOODTYP
 (
 EXC_GOOD_TYP
 ) ON UPDATE  NO ACTION 
  ON DELETE  NO ACTION 
 
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 FK_ZAIDM_EX_BRAND_ZAIDM_EX_MARKET FOREIGN KEY
 (
 MARKET_ID
 ) REFERENCES dbo.ZAIDM_EX_MARKET
 (
 MARKET_ID
 ) ON UPDATE  NO ACTION 
  ON DELETE  NO ACTION 
 
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 FK_ZAIDM_EX_BRAND_ZAIDM_EX_PRODTYP FOREIGN KEY
 (
 PROD_CODE
 ) REFERENCES dbo.ZAIDM_EX_PRODTYP
 (
 PROD_CODE
 ) ON UPDATE  NO ACTION 
  ON DELETE  NO ACTION 
 
GO
ALTER TABLE dbo.ZAIDM_EX_BRAND ADD CONSTRAINT
 FK_ZAIDM_EX_BRAND_ZAIDM_EX_SERIES FOREIGN KEY
 (
 SERIES_CODE
 ) REFERENCES dbo.ZAIDM_EX_SERIES
 (
 SERIES_CODE
 ) ON UPDATE  NO ACTION 
  ON DELETE  NO ACTION 
 
GO
COMMIT