BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CK2
	DROP CONSTRAINT FK_CK2_PBCK3_PBCK7
GO
ALTER TABLE dbo.PBCK3_PBCK7 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK3 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.CK2.PBCK3_PBCK7_ID', N'Tmp_PBCK3_ID', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.CK2.Tmp_PBCK3_ID', N'PBCK3_ID', 'COLUMN' 
GO
ALTER TABLE dbo.CK2 ADD CONSTRAINT
	FK_CK2_PBCK3 FOREIGN KEY
	(
	PBCK3_ID
	) REFERENCES dbo.PBCK3
	(
	PBCK3_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CK2 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
