BEGIN TRANSACTION
GO
ALTER TABLE dbo.BACK1
	DROP CONSTRAINT FK_BACK1_CK5
GO
ALTER TABLE dbo.CK5 SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE dbo.BACK1
	DROP CONSTRAINT FK_BACK1_PBCK7
GO
ALTER TABLE dbo.PBCK7 SET (LOCK_ESCALATION = TABLE)
GO

CREATE TABLE dbo.Tmp_BACK1
	(
	BACK1_ID int NOT NULL IDENTITY (1, 1),
	BACK1_NUMBER nvarchar(30) NOT NULL,
	BACK1_DATE datetime NOT NULL,
	PBCK7_ID int NULL,
	CK5_ID bigint NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_BACK1 SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_BACK1 ON
GO
IF EXISTS(SELECT * FROM dbo.BACK1)
	 EXEC('INSERT INTO dbo.Tmp_BACK1 (BACK1_ID, BACK1_NUMBER, BACK1_DATE, PBCK7_ID, CK5_ID)
		SELECT BACK1_ID, BACK1_NUMBER, BACK1_DATE, PBCK7_ID, CK5_ID FROM dbo.BACK1 WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_BACK1 OFF
GO
ALTER TABLE dbo.BACK1_DOCUMENT
	DROP CONSTRAINT FK_BACK1_DOCUMENT_BACK1
GO
DROP TABLE dbo.BACK1
GO
EXECUTE sp_rename N'dbo.Tmp_BACK1', N'BACK1', 'OBJECT' 
GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	PK_BACK1 PRIMARY KEY CLUSTERED 
	(
	BACK1_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	FK_BACK1_PBCK7 FOREIGN KEY
	(
	PBCK7_ID
	) REFERENCES dbo.PBCK7
	(
	PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	FK_BACK1_CK5 FOREIGN KEY
	(
	CK5_ID
	) REFERENCES dbo.CK5
	(
	CK5_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

ALTER TABLE dbo.BACK1_DOCUMENT ADD CONSTRAINT
	FK_BACK1_DOCUMENT_BACK1 FOREIGN KEY
	(
	BACK1
	) REFERENCES dbo.BACK1
	(
	BACK1_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BACK1_DOCUMENT SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

