BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.BACK1
	DROP CONSTRAINT FK_BACK1_PBCK3_PBCK7
GO
ALTER TABLE dbo.PBCK3_PBCK7 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK7 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.BACK1.PBCK3_PBCK7_ID', N'Tmp_PBCK7_ID', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.BACK1.Tmp_PBCK7_ID', N'PBCK7_ID', 'COLUMN' 
GO
ALTER TABLE dbo.BACK1 ADD CONSTRAINT
	FK_BACK1_PBCK7 FOREIGN KEY
	(
	PBCK7_ID
	) REFERENCES dbo.PBCK7
	(
	PBCK7_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BACK1 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
