ALTER TABLE dbo.PBCK4_ITEM
	DROP CONSTRAINT FK_PBCK4_ITEM_CK1
GO
DROP table [dbo].[CK1]
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CK1](
 [CK1_ID] [bigint] IDENTITY(1,1) NOT NULL,
 [CK1_NUMBER] [nvarchar](35) NOT NULL,
 [CK1_DATE] [date] NOT NULL,
 [PLANT_ID] [nvarchar](4) NULL,
 [CREATED_DATE] [datetime] NULL,
 [CREATED_BY] [nvarchar](50) NULL,
 [COMPANY_ID] [nvarchar](4) NULL,
 [COMPANY_NAME] [nvarchar](35) NULL,
 [VENDOR_ID] [nvarchar](10) NULL,
 [NPPBKC_ID] [nvarchar](15) NULL,
 [ORDER_DATE] [datetime] NULL,
 CONSTRAINT [PK_CK1] PRIMARY KEY CLUSTERED 
(
 [CK1_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[CK1_ITEM](
 [CK1_ITEM_ID] [bigint] IDENTITY(1,1) NOT NULL,
 [CK1_ID] [bigint] NULL,
 [MATERIAL_ID] [nvarchar](18) NULL,
 [WERKS] [nvarchar](4) NULL,
 [FA_CODE] [nvarchar](18) NULL,
 [MENGE] [decimal](18, 2) NULL,
 [UOM] [nvarchar](5) NULL,
 CONSTRAINT [PK_CK1_ITEM] PRIMARY KEY CLUSTERED 
(
 [CK1_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE dbo.CK1_ITEM ADD CONSTRAINT
	FK_CK1_ITEM_CK1 FOREIGN KEY
	(
	CK1_ID
	) REFERENCES dbo.CK1
	(
	CK1_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.CK1_ITEM SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.PBCK4_ITEM ADD CONSTRAINT
	FK_PBCK4_ITEM_CK1 FOREIGN KEY
	(
	CK1_ID
	) REFERENCES dbo.[CK1]
	(
	CK1_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO