DROP TABLE [dbo].[CK5_MATERIAL]
GO

CREATE TABLE [dbo].[CK5_MATERIAL](
	[CK5_MATERIAL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CK5_ID] [bigint] NULL,
	[MATERIAL_ID] [bigint] NULL,
	[LINE_ITEM] [int] NULL,
	[QTY] [numeric](18, 0) NULL,
	[CONVERTED_QTY] [numeric](18, 0) NULL,
	[CONVERTED_UOM_ID] [int] NULL,
	[BRAND] [varchar](50) NULL,
	[PLANT_ID] [bigint] NULL,
	[UOM] [varchar](50) NULL,
	[CONVERTION] [numeric](18, 2) NULL,
	[HJE] [numeric](18, 2) NULL,
	[TARIFF] [numeric](18, 2) NULL,
	[EXCISE_VALUE] [numeric](18, 2) NULL,
	[USD_VALUE] [numeric](18, 2) NULL,
	[NOTE] [varchar](100) NULL,
	[CONVERTED_UOM] [varchar](50) NULL,
 CONSTRAINT [PK_CK5_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[CK5_MATERIAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CK5_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_CK5_MATERIAL_CK5] FOREIGN KEY([CK5_ID])
REFERENCES [dbo].[CK5] ([CK5_ID])
GO

ALTER TABLE [dbo].[CK5_MATERIAL] CHECK CONSTRAINT [FK_CK5_MATERIAL_CK5]
GO
