//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CK1_EXCISE_CALCULATE_ADJUST
    {
        public long CK1_ID { get; set; }
        public System.DateTime CK1_DATE { get; set; }
        public Nullable<int> BULAN { get; set; }
        public Nullable<int> TAHUN { get; set; }
        public string PRODUCT_ALIAS { get; set; }
        public string CK1_NUMBER { get; set; }
        public Nullable<decimal> ORDERQTY { get; set; }
        public Nullable<decimal> NOMINAL { get; set; }
        public string NPPBKC_ID { get; set; }
        public string BRAND_CONTENT { get; set; }
        public Nullable<decimal> SERIES_VALUE { get; set; }
        public string BRAND_CE { get; set; }
        public Nullable<decimal> PRODUCTION { get; set; }
    }
}
