//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENTEMAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENTEMAIL()
        {
            this.EMAILVARIABELS = new HashSet<EMAILVARIABEL>();
        }
    
        public long CONTENTEMAILID { get; set; }
        public string EMAILNAME { get; set; }
        public string EMAILCONTENT { get; set; }
        public string EMAILSUBJECT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILVARIABEL> EMAILVARIABELS { get; set; }
    }
}
