//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILVARIABEL
    {
        public long VARIABELID { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> CONTENTEMAILID { get; set; }
    
        public virtual CONTENTEMAIL CONTENTEMAIL { get; set; }
    }
}
