//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCISE_CREDIT_APPROVED_DETAIL
    {
        public long EXSICE_CREDIT_ID { get; set; }
        public decimal AMOUNT_APPROVED { get; set; }
        public string PROD_CODE { get; set; }
    
        public virtual EXCISE_CREDIT EXCISE_CREDIT { get; set; }
        public virtual MASTER_PRODUCT_TYPE ZAIDM_EX_PRODTYP { get; set; }
    }
}
