//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVIEW_REQUEST_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERVIEW_REQUEST_DETAIL()
        {
            this.MANUFACTURING_BOUND_CONDITION = new HashSet<MANUFACTURING_BOUND_CONDITION>();
        }
    
        public long VR_FORM_ID { get; set; }
        public string MANUFACTURE_ADDRESS { get; set; }
        public long CITY_ID { get; set; }
        public long PROVINCE_ID { get; set; }
        public string SUB_DISTRICT { get; set; }
        public string VILLAGE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public long VR_FORM_DETAIL_ID { get; set; }
    
        public virtual INTERVIEW_REQUEST INTERVIEW_REQUEST { get; set; }
        public virtual MASTER_CITY MASTER_CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURING_BOUND_CONDITION> MANUFACTURING_BOUND_CONDITION { get; set; }
        public virtual MASTER_STATE MASTER_STATE { get; set; }
    }
}
