//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANUFACTURING_LISENCE_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANUFACTURING_LISENCE_REQUEST()
        {
            this.MANUFACTURING_BOUND_CONDITION = new HashSet<MANUFACTURING_BOUND_CONDITION>();
            this.MANUFACTURING_PRODUCT_TYPE = new HashSet<MANUFACTURING_PRODUCT_TYPE>();
            this.MANUFACTURING_PRODUCT_TYPE1 = new HashSet<MANUFACTURING_PRODUCT_TYPE>();
        }
    
        public long VR_FORM_ID { get; set; }
        public string MNF_FORM_NUMBER { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED_DATE { get; set; }
        public string LASTAPPROVED_BY { get; set; }
        public Nullable<System.DateTime> LASTAPPROVED_DATE { get; set; }
        public long LASTAPPROVED_STATUS { get; set; }
        public long MNF_REQUEST_ID { get; set; }
        public string DECREE_NO { get; set; }
        public Nullable<System.DateTime> DECREE_DATE { get; set; }
        public string NPPBKC_ID { get; set; }
        public Nullable<bool> DECREE_STATUS { get; set; }
    
        public virtual INTERVIEW_REQUEST INTERVIEW_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURING_BOUND_CONDITION> MANUFACTURING_BOUND_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURING_PRODUCT_TYPE> MANUFACTURING_PRODUCT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURING_PRODUCT_TYPE> MANUFACTURING_PRODUCT_TYPE1 { get; set; }
        public virtual MASTER_NPPBKC ZAIDM_EX_NPPBKC { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual SYS_REFFERENCES SYS_REFFERENCES { get; set; }
        public virtual USER USER2 { get; set; }
    }
}
