//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_NPPBKC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTER_NPPBKC()
        {
            this.PLANTS = new HashSet<MASTER_PLANT>();
            this.POA_MAP = new HashSet<POA_MAP>();
            this.INTERVIEW_REQUEST = new HashSet<INTERVIEW_REQUEST>();
            this.MANUFACTURING_LISENCE_REQUEST = new HashSet<MANUFACTURING_LISENCE_REQUEST>();
            this.REPLACEMENT_DOCUMENTS = new HashSet<REPLACEMENT_DOCUMENTS>();
            this.EXCISE_CREDIT = new HashSet<EXCISE_CREDIT>();
            this.BRAND_REGISTRATION_REQ = new HashSet<BRAND_REGISTRATION_REQ>();
            this.RECEIVED_DECREE = new HashSet<RECEIVED_DECREE>();
        }
    
        public string NPPBKC_ID { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string CITY_ALIAS { get; set; }
        public string KPPBC_ID { get; set; }
        public string REGION { get; set; }
        public string REGION_DGCE { get; set; }
        public string VENDOR_ID { get; set; }
        public string BUKRS { get; set; }
        public string TEXT_TO { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<bool> FLAG_FOR_LACK1 { get; set; }
        public string DGCE_ADDRESS { get; set; }
        public string LOCATION { get; set; }
        public string KPPBC_ADDRESS { get; set; }
    
        public virtual T001 COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_PLANT> PLANTS { get; set; }
        public virtual LFA1 VENDORS { get; set; }
        public virtual MASTER_KPPBC KPPBC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POA_MAP> POA_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERVIEW_REQUEST> INTERVIEW_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANUFACTURING_LISENCE_REQUEST> MANUFACTURING_LISENCE_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPLACEMENT_DOCUMENTS> REPLACEMENT_DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXCISE_CREDIT> EXCISE_CREDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BRAND_REGISTRATION_REQ> BRAND_REGISTRATION_REQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIVED_DECREE> RECEIVED_DECREE { get; set; }
    }
}
