//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POA()
        {
            this.POA_MAPS = new HashSet<POA_MAP>();
            this.POA_EXCISER = new HashSet<POA_EXCISER>();
            this.INTERVIEW_REQUEST = new HashSet<INTERVIEW_REQUEST>();
            this.EXCISE_CREDIT = new HashSet<EXCISE_CREDIT>();
        }
    
        public string POA_ID { get; set; }
        public string ID_CARD { get; set; }
        public string POA_PHONE { get; set; }
        public string POA_ADDRESS { get; set; }
        public string POA_EMAIL { get; set; }
        public string PRINTED_NAME { get; set; }
        public string TITLE { get; set; }
        public string LOGIN_AS { get; set; }
        public string MANAGER_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER_LOGIN { get; set; }
        public virtual USER USER2 { get; set; }
        public virtual USER MANAGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POA_MAP> POA_MAPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POA_EXCISER> POA_EXCISER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERVIEW_REQUEST> INTERVIEW_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXCISE_CREDIT> EXCISE_CREDIT { get; set; }
    }
}
