//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DEVELOPMENT_UPLOAD
    {
        public long FILE_ID { get; set; }
        public Nullable<long> PD_DETAIL_ID { get; set; }
        public Nullable<int> ITEM_ID { get; set; }
        public string PATH_URL { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public Nullable<long> DOCUMENT_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string FILE_NAME { get; set; }
    
        public virtual MASTER_SUPPORTING_DOCUMENT MASTER_SUPPORTING_DOCUMENT { get; set; }
        public virtual PRODUCT_DEVELOPMENT_DETAIL PRODUCT_DEVELOPMENT_DETAIL { get; set; }
    }
}
