//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVED_DECREE_DETAIL
    {
        public string BRAND_CE { get; set; }
        public string PROD_CODE { get; set; }
        public int COMPANY_TIER { get; set; }
        public decimal HJE { get; set; }
        public string UNIT { get; set; }
        public string BRAND_CONTENT { get; set; }
        public decimal TARIFF { get; set; }
        public long RECEIVED_ID { get; set; }
        public long PD_DETAIL_ID { get; set; }
        public long RECEIVED_DETAIL_ID { get; set; }
    
        public virtual PRODUCT_DEVELOPMENT_DETAIL PRODUCT_DEVELOPMENT_DETAIL { get; set; }
        public virtual MASTER_PRODUCT_TYPE ZAIDM_EX_PRODTYP { get; set; }
        public virtual RECEIVED_DECREE RECEIVED_DECREE { get; set; }
    }
}
