//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPLACEMENT_DOCUMENTS_DETAIL
    {
        public long FORM_DET_ID { get; set; }
        public long FORM_ID { get; set; }
        public string UPDATE_NOTES { get; set; }
    
        public virtual REPLACEMENT_DOCUMENTS REPLACEMENT_DOCUMENTS { get; set; }
    }
}
