//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PRINTOUT_LAYOUT
    {
        public long USER_PRINTOUT_LAYOUT_ID { get; set; }
        public int PRINTOUT_LAYOUT_ID { get; set; }
        public string USER_ID { get; set; }
        public string LAYOUT { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual PRINTOUT_LAYOUT PRINTOUT_LAYOUT { get; set; }
        public virtual USER USER { get; set; }
    }
}
