//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBrandRegistration
    {
        public long REGISTRATION_ID { get; set; }
        public string REGISTRATION_NO { get; set; }
        public string SUBMISSION_DATE { get; set; }
        public int REGISTRATION_TYPE { get; set; }
        public string NPPBKC_ID { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string BUKRS { get; set; }
        public string BUTXT { get; set; }
        public string BUTXT_ALIAS { get; set; }
        public string EFFECTIVE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string CREATED_DATE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public string LASTMODIFIED_DATE { get; set; }
        public string LASTAPPROVED_BY { get; set; }
        public string LASTAPPROVED_DATE { get; set; }
        public long LASTAPPROVED_STATUS { get; set; }
        public string REFF_VALUE { get; set; }
        public Nullable<bool> DECREE_STATUS { get; set; }
        public string DECREE_NO { get; set; }
        public string DECREE_DATE { get; set; }
        public string DECREE_STARTDATE { get; set; }
        public string BRAND_CE { get; set; }
        public string LATEST_SKEP_NO { get; set; }
        public string PROD_CODE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PRODUCT_ALIAS { get; set; }
        public int COMPANY_TIER { get; set; }
        public decimal HJE { get; set; }
        public string UNIT { get; set; }
        public string BRAND_CONTENT { get; set; }
        public Nullable<decimal> TARIFF { get; set; }
        public string MATERIAL_PACKAGE { get; set; }
        public string MARKET_ID { get; set; }
        public string MARKET_DESC { get; set; }
        public string FRONT_SIDE { get; set; }
        public string BACK_SIDE { get; set; }
        public string LEFT_SIDE { get; set; }
        public string RIGHT_SIDE { get; set; }
        public string TOP_SIDE { get; set; }
        public string BOTTOM_SIDE { get; set; }
    }
}
