//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sampoerna.EMS.CustomService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMLInterviewRequest
    {
        public long VR_FORM_ID { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public string PERIHAL { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string LASTMODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED_DATE { get; set; }
        public long LASTAPPROVED_STATUS { get; set; }
        public string LASTAPPROVED_STATUS_VALUE { get; set; }
        public string LASTAPPROVED_BY { get; set; }
        public Nullable<System.DateTime> LASTAPPROVED_DATE { get; set; }
        public string FORM_NUMBER { get; set; }
        public string BA_NUMBER { get; set; }
        public Nullable<System.DateTime> BA_DATE { get; set; }
        public string NPPBKC_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string NPWP { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string BA_STATUS { get; set; }
        public string POA_ID { get; set; }
        public string PRINTED_NAME { get; set; }
        public string POA_ADDRESS { get; set; }
        public string TITLE { get; set; }
        public string KPPBC { get; set; }
        public string KPPBC_ADDRESS { get; set; }
        public string MANUFACTURE_ADDRESS { get; set; }
        public string CITY_NAME { get; set; }
        public string STATE_NAME { get; set; }
        public string SUB_DISTRICT { get; set; }
        public string VILLAGE { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
    }
}
