
/****** Object:  Table [dbo].[MASTER_DATA_APPROVAL]    Script Date: 4/19/2017 9:41:50 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MASTER_DATA_APPROVAL](
	[APPROVAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[PAGE_ID] [int] NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[APPROVED_BY] [nvarchar](50) NULL,
	[APPROVED_DATE] [datetime] NULL,
	[STATUS_ID] [int] NOT NULL,
	[FORM_ID] [varchar](100) NULL,
 CONSTRAINT [PK_MASTER_DATA_APPROVAL] PRIMARY KEY CLUSTERED 
(
	[APPROVAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL]  WITH CHECK ADD  CONSTRAINT [FK_MASTER_DATA_APPROVAL_APPROVER] FOREIGN KEY([APPROVED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL] CHECK CONSTRAINT [FK_MASTER_DATA_APPROVAL_APPROVER]
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL]  WITH CHECK ADD  CONSTRAINT [FK_MASTER_DATA_APPROVAL_PAGE] FOREIGN KEY([PAGE_ID])
REFERENCES [dbo].[PAGE] ([PAGE_ID])
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL] CHECK CONSTRAINT [FK_MASTER_DATA_APPROVAL_PAGE]
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL]  WITH CHECK ADD  CONSTRAINT [FK_MASTER_DATA_APPROVAL_USER] FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL] CHECK CONSTRAINT [FK_MASTER_DATA_APPROVAL_USER]
GO



/****** Object:  Table [dbo].[MASTER_DATA_APPROVAL_DETAIL]    Script Date: 4/19/2017 9:43:22 AM ******/

CREATE TABLE [dbo].[MASTER_DATA_APPROVAL_DETAIL](
	[APPROVAL_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[APPROVAL_ID] [int] NOT NULL,
	[COLUMN_NAME] [varchar](100) NOT NULL,
	[COLUMN_DESCRIPTION] [varchar](500) NOT NULL,
	[OLD_VALUE] [varchar](2000) NULL,
	[NEW_VALUE] [varchar](2000) NULL,
 CONSTRAINT [PK_MASTER_DATA_APPROVAL_DETAIL] PRIMARY KEY CLUSTERED 
(
	[APPROVAL_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_MASTER_DATA_APPROVAL_DETAIL_MASTER_DATA_APPROVAL] FOREIGN KEY([APPROVAL_ID])
REFERENCES [dbo].[MASTER_DATA_APPROVAL] ([APPROVAL_ID])
GO

ALTER TABLE [dbo].[MASTER_DATA_APPROVAL_DETAIL] CHECK CONSTRAINT [FK_MASTER_DATA_APPROVAL_DETAIL_MASTER_DATA_APPROVAL]
GO

