

/****** Object:  Table [dbo].[QUOTA_MONITORING]    Script Date: 4/26/2017 10:02:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[QUOTA_MONITORING](
	[MONITORING_ID] [int] IDENTITY(1,1) NOT NULL,
	[NPPBKC_ID] [varchar](20) NULL,
	[SUPPLIER_NPPBKC_ID] [varchar](20) NULL,
	[SUPPLIER_WERKS] [varchar](50) NULL,
	[PERIOD_FROM] [datetime] NULL,
	[PERIOD_TO] [datetime] NULL,
	[QUOTA_APPROVED] [decimal](18, 2) NULL,
	[QUOTA_USED] [decimal](18, 2) NULL,
	[QUOTA_REMAIN] [decimal](18, 2) NULL,
 CONSTRAINT [PK_QUOTA_MONITORING] PRIMARY KEY CLUSTERED 
(
	[MONITORING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



/****** Object:  Table [dbo].[QUOTA_MONITORING_DETAIL]    Script Date: 4/26/2017 10:02:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[QUOTA_MONITORING_DETAIL](
	[MONITORING_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[MONITORING_ID] [int] NULL,
	[USER_ID] [varchar](10) NULL,
	[ROLE_ID] [int] NULL,
	[EMAIL_STATUS] [int] NULL,
 CONSTRAINT [PK_QUOTA_MONITORING_DETAIL] PRIMARY KEY CLUSTERED 
(
	[MONITORING_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[QUOTA_MONITORING_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_QUOTA_MONITORING_DETAIL_QUOTA_MONITORING] FOREIGN KEY([MONITORING_ID])
REFERENCES [dbo].[QUOTA_MONITORING] ([MONITORING_ID])
GO

ALTER TABLE [dbo].[QUOTA_MONITORING_DETAIL] CHECK CONSTRAINT [FK_QUOTA_MONITORING_DETAIL_QUOTA_MONITORING]
GO


