/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.DOC_NUMBER_SEQ.DOC_NUMBER_SEQ1', N'Tmp_DOC_NUMBER_SEQ_ID_5', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.DOC_NUMBER_SEQ.Tmp_DOC_NUMBER_SEQ_ID_5', N'DOC_NUMBER_SEQ_ID', 'COLUMN' 
GO
ALTER TABLE dbo.DOC_NUMBER_SEQ SET (LOCK_ESCALATION = TABLE)
GO
COMMIT