USE [EMS-DEV2]
GO

/****** Object:  Table [dbo].[USER_PLANT_MAP]    Script Date: 8/12/2015 8:30:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_PLANT_MAP](
	[USER_PLANT_MAP_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [nvarchar](50) NOT NULL,
	[PLANT_ID] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_USER_PLANT_MAP] PRIMARY KEY CLUSTERED 
(
	[USER_PLANT_MAP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[USER_PLANT_MAP]  WITH CHECK ADD  CONSTRAINT [FK_USER_PLANT_MAP_T001W] FOREIGN KEY([PLANT_ID])
REFERENCES [dbo].[T001W] ([WERKS])
GO

ALTER TABLE [dbo].[USER_PLANT_MAP] CHECK CONSTRAINT [FK_USER_PLANT_MAP_T001W]
GO

ALTER TABLE [dbo].[USER_PLANT_MAP]  WITH CHECK ADD  CONSTRAINT [FK_USER_PLANT_MAP_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([USER_ID])
GO

ALTER TABLE [dbo].[USER_PLANT_MAP] CHECK CONSTRAINT [FK_USER_PLANT_MAP_USER]
GO


