USE [EMS]
ALTER TABLE [dbo].[ZAIDM_EX_MATERIAL]
ADD IS_DELETE bit NULL
ALTER TABLE [dbo].[ZAIDM_EX_POA]
DROP PHONE
ALTER TABLE [dbo].[VIRTUAL_PLANT_MAP]
ADD IS_DELETED  bit NULL
ALTER TABLE [dbo].[VIRTUAL_PLANT_MAP]
ADD CREATED_BY  int NULL
ALTER TABLE [dbo].[VIRTUAL_PLANT_MAP]
ADD CREATED_DATE datetime NULL
ALTER TABLE [dbo].[VIRTUAL_PLANT_MAP] CHECK CONSTRAINT [FK_VIRTUAL_PLANT_MAP_USER]
GO