BEGIN TRANSACTION
GO
ALTER TABLE dbo.PBCK1 ADD CONSTRAINT
	FK_PBCK1_USER FOREIGN KEY
	(
	APPROVED_BY_MANAGER
	) REFERENCES dbo.[USER]
	(
	USER_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PBCK1 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
