BEGIN TRANSACTION
GO
ALTER TABLE dbo.T001W SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.T001K
	DROP CONSTRAINT FK_T001K_T1001
GO
ALTER TABLE dbo.T001 SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.T001K ADD CONSTRAINT
	FK_T001K_T001W FOREIGN KEY
	(
	BWKEY
	) REFERENCES dbo.T001W
	(
	WERKS
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.T001K SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
