ALTER TABLE dbo.REVERSAL ADD
	INVENTORY_MOVEMENT_ID bigint NULL
GO

ALTER TABLE dbo.REVERSAL ADD CONSTRAINT
	FK_REVERSAL_INVENTORY_MOVEMENT FOREIGN KEY
	(
	INVENTORY_MOVEMENT_ID
	) REFERENCES dbo.INVENTORY_MOVEMENT
	(
	INVENTORY_MOVEMENT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO