
delete from COUNTRY; -- wipe current country data

/*fill country db with data*/
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('99','Undefined');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AD','Andorra');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AE','UAE');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AF','Afghanistan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AG','Antigua/Barbuda');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AI','Anguilla');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AL','Albania');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AM','Armenia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AN','Dutch Antilles');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AO','Angola');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AQ','Antarctica');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AR','Argentina');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AS','American Samoa');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AT','Austria');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AU','Australia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AW','Aruba');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AX','Aland Islands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('AZ','Azerbaijan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BA','Bosnia-Herz.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BB','Barbados');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BD','Bangladesh');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BE','Belgium');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BF','Burkina Faso');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BG','Bulgaria');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BH','Bahrain');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BI','Burundi');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BJ','Benin');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BL','St. Barthélemy');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BM','Bermuda');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BN','Brunei');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BO','Bolivia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BQ','Bonaire, Saba');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BR','Brazil');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BS','Bahamas');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BT','Bhutan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BV','Bouvet Island');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BW','Botswana');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BY','Belarus');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('BZ','Belize');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CA','Canada');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CC','Cocos (Keeling)');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CD','Dem. Rep. Congo');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CF','Central Afr.Rep');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CG','Congo');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CH','Switzerland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CI','Ivory Coast');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CK','Cook Islands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CL','Chile');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CM','Cameroon');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CN','China');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CO','Colombia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CR','Costa Rica');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CS','Serbia/Monteneg');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CU','Cuba');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CV','Cape Verde');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CW','Curaçao');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CX','Christmas Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CY','Cyprus');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('CZ','Czech Republic');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DE','Germany');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DJ','Djibouti');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DK','Denmark');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DM','Dominica');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DO','Dominican Rep.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('DZ','Algeria');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('EC','Ecuador');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('EE','Estonia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('EG','Egypt');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('EH','West Sahara');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ER','Eritrea');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ES','Spain');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ET','Ethiopia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FI','Finland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FJ','Fiji');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FK','Falkland Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FM','Micronesia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FO','Faroe Islands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('FR','France');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GA','Gabon');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GB','United Kingdom');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GD','Grenada');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GE','Georgia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GF','French Guiana');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GG','Guernsey');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GH','Ghana');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GI','Gibraltar');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GL','Greenland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GM','Gambia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GN','Guinea');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GP','Guadeloupe');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GQ','Equatorial Gui.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GR','Greece');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GS','S. Sandwich Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GT','Guatemala');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GU','Guam');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GW','Guinea-Bissau');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('GY','Guyana');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HK','Hong Kong');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HM','Heard/McDon.Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HN','Honduras');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HR','Croatia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HT','Haiti');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('HU','Hungary');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ID','Indonesia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IE','Ireland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IL','Israel');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IM','Isle of Man');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IN','India');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IO','Brit. Ind.Ocean');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IQ','Iraq');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IR','Iran');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IS','Iceland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('IT','Italy');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('JE','Jersey');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('JM','Jamaica');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('JO','Jordan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('JP','Japan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KE','Kenya');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KG','Kyrgyzstan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KH','Cambodia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KI','Kiribati');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KM','Comoros');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KN','St Kitts&Nevis');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KP','North Korea');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KR','Korea');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KW','Kuwait');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KY','Cayman Islands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('KZ','Kazakhstan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LA','Laos');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LB','Lebanon');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LC','Saint Lucia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LI','Liechtenstein');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LK','Sri Lanka');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LR','Liberia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LS','Lesotho');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LT','Lithuania');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LU','Luxembourg');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LV','Latvia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('LY','Libya');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MA','Morocco');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MC','Monaco');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MD','Moldova');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ME','Montenegro');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MF','Saint Martin');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MG','Madagascar');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MH','Marshall Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MK','Macedonia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ML','Mali');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MM','Myanmar');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MN','Mongolia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MO','Macau');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MP','N. Mariana Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MQ','Martinique');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MR','Mauritania');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MS','Montserrat');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MT','Malta');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MU','Mauritius');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MV','Maldives');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MW','Malawi');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MX','Mexico');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MY','Malaysia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('MZ','Mozambique');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NA','Namibia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NC','New Caledonia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NE','Niger');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NF','Norfolk Island');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NG','Nigeria');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NI','Nicaragua');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NL','Netherlands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NO','Norway');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NP','Nepal');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NR','Nauru');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NU','Niue');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('NZ','New Zealand');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('OM','Oman');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PA','Panama');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PE','Peru');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PF','Frenc.Polynesia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PG','Papua Nw Guinea');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PH','Philippines');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PK','Pakistan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PL','Poland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PM','St.Pier,Miquel.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PN','Pitcairn');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PR','Puerto Rico');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PS','Palestine');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PT','Portugal');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PW','Palau');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('PY','Paraguay');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('QA','Qatar');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('RE','Reunion');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('RO','Romania');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('RS','Serbia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('RU','Russian Fed.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('RW','Rwanda');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SA','Saudi Arabia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SB','Solomon Islands');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SC','Seychelles');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SD','Sudan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SE','Sweden');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SG','Singapore');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SH','St. Helena');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SI','Slovenia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SJ','Svalbard');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SK','Slovakia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SL','Sierra Leone');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SM','San Marino');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SN','Senegal');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SO','Somalia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SR','Suriname');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SS','South Sudan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ST','S.Tome,Principe');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SV','El Salvador');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SX','Sint Maarten');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SY','Syria');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('SZ','Swaziland');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TC','Turks & Caicos');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TD','Chad');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TF','French S.Territ');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TG','Togo');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TH','Thailand');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TJ','Tajikstan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TK','Tokelau');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TL','Timor-Leste');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TM','Turkmenistan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TN','Tunisia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TO','Tonga');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TP','East Timor');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TR','Turkey');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TT','Trinidad,Tobago');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TV','Tuvalu');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TW','Taiwan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('TZ','Tanzania');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('UA','Ukraine');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('UG','Uganda');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('UM','US Min Outl.Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('US','USA');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('UY','Uruguay');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('UZ','Uzbekistan');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VA','Vatican City');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VC','St. Vincent');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VE','Venezuela');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VG','Brit.Virgin Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VI','Amer.Virgin Is.');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VN','Vietnam');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('VU','Vanuatu');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('WF','Wallis,Futuna');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('WS','West Samoa');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('XK','Kosovo');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('YE','Yemen');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('YT','Mayotte');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ZA','South Africa');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ZM','Zambia');
insert into COUNTRY(COUNTRY_CODE ,COUNTRY_NAME) values('ZW','Zimbabwe');
