use EMS;

update T001
set BUTXT_ALIAS = 'HMS-E',MODIFIED_BY = 'SCRIPTED', MODIFIED_DATE = CURRENT_TIMESTAMP
where BUKRS = '3066';

update T001
set BUTXT_ALIAS = 'SIS-E',MODIFIED_BY = 'SCRIPTED', MODIFIED_DATE = CURRENT_TIMESTAMP
where BUKRS = '1670';

update T001
set BUTXT_ALIAS = 'PMID-E',MODIFIED_BY = 'SCRIPTED', MODIFIED_DATE = CURRENT_TIMESTAMP
where BUKRS = '1616';